# 🚀 LAB GUIDE — PRODUCTION-GRADE GRAPHRAG VS FLAT RAG

**Thời lượng:** 120 phút  
**Môi trường:** Google Colab (T4 GPU khuyến nghị) + Neo4j AuraDB  
**Dữ liệu:** HackerNoon Tech Company News Data Dump (bản thu gọn do giảng viên cung cấp)  
**Công cụ:** Học viên được dùng AI Coding Agent, nhưng phải tự thiết kế, kiểm thử và giải thích logic.

## 🎯 Mục tiêu
1. Xây dựng Hybrid GraphRAG end-to-end.
2. Xử lý Coreference Resolution, Entity Resolution và Super-node Mitigation.
3. Bulk insert bằng `UNWIND`, không insert từng row.
4. So sánh Flat RAG và GraphRAG bằng Golden Dataset + LLM-as-a-Judge.
5. Đo quality, latency và token usage.
6. Giải thích kiến trúc và failure modes.

> Notebook là **reference lab guide**: có code khung chạy được nhưng vẫn yêu cầu học viên thay prompt/threshold/retrieval policy và thuyết minh lựa chọn.

## ⏳ Timeline

| Phút | Nội dung |
|---|---|
| 00–15 | Setup, load, dedup, chunk, coreference |
| 15–45 | NER/RE, entity resolution, Neo4j bulk insert |
| 45–75 | Flat RAG, graph traversal, hybrid retrieval |
| 75–105 | Golden Dataset, LLM-as-a-Judge, comparison |
| 105–120 | Failure-mode tests, bonus, export, thuyết minh |

### Scale guard
Trong lab 2 giờ, không nên gửi toàn bộ 350MB qua LLM. Mặc định dùng subset:
- `LAB_MAX_ARTICLES = 1500`
- `LAB_MAX_CHUNKS = 3000`
- `EXTRACTION_MAX_CHUNKS = 400`

Kiến trúc phải scale được; volume trong giờ lab chỉ dùng để chứng minh pipeline.

# PHẦN 1 — SETUP & PREPROCESSING

### Secrets trên Colab
Tạo:
- `NEO4J_URI`, `NEO4J_USER`, `NEO4J_PASSWORD`
- `GROQ_API_KEY`, `GROQ_MODEL`
- `HF_TOKEN` để stream dataset từ Hugging Face
- cho judge: `JUDGE_PROVIDER`, `JUDGE_MODEL`, và `OPENAI_API_KEY` nếu dùng OpenAI

Không hard-code API key vào notebook nộp bài.

In [2]:
%pip -q uninstall -y transformers sentence-transformers tokenizers huggingface_hub safetensors peft -q
%pip -q install --no-cache-dir neo4j pandas numpy pyarrow "sentence-transformers==3.0.1" "transformers==4.44.2" "tokenizers==0.19.1" "huggingface_hub==0.24.6" "safetensors==0.4.5" faiss-cpu groq openai tqdm networkx spacy datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.1/227.1 kB 18.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 171.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 262.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 417.5/417.5 kB 286.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 434.8/434.8 kB 283.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 327.8/327.8 kB 275.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 211.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 186.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
diffusers 0.39.0 requires huggingface-hub<2.0,>=0.34.0, but you have huggingface-hub 0.24.6 which is incompatible.
diffusers 0.39.0 requires safetensors>=0.8.0, but you have safetensors 0.4.5 which is incompatible.
gradio 6.24.0 requires huggingface-hub<2.0,>=1.16.0, but you have huggingface-hub 0.24.6 which is incompatible.

In [3]:
#@title 1.1b - [COLAB] Clone repo & chuyen working directory
# Chay cell nay TRUOC cell 1.2.
# Neu dang chay local ngay trong repo, cell tu bo qua phan clone.
import os, sys, subprocess
from pathlib import Path

GH_USER   = "ThaiTu2602"
GH_REPO   = "K4-Track3-Lab19-GraphRAG_2A202601504"
CLONE_DIR = "/content/lab19"

IN_COLAB = "google.colab" in sys.modules

if IN_COLAB and not Path(CLONE_DIR, "ASSIGNMENT.md").exists():
    from google.colab import userdata
    GH_TOKEN = (userdata.get("GH_TOKEN") or "").strip()
    if not GH_TOKEN:
        raise ValueError("GH_TOKEN rong sau khi strip(). Kiem tra lai Colab Secrets.")
    url = f"https://{GH_USER}:{GH_TOKEN}@github.com/{GH_USER}/{GH_REPO}.git"
    r = subprocess.run(["git", "clone", "--quiet", url, CLONE_DIR],
                       capture_output=True, text=True)
    if r.returncode != 0:
        # Che token truoc khi in loi, tranh lo secret vao output notebook.
        raise RuntimeError("Clone that bai: " + (r.stderr or "").replace(GH_TOKEN, "***"))
    # Go token khoi remote de no khong bao gio xuat hien trong log/output.
    subprocess.run(["git", "-C", CLONE_DIR, "remote", "set-url", "origin",
                    f"https://github.com/{GH_USER}/{GH_REPO}.git"], check=True)
    subprocess.run(["git", "-C", CLONE_DIR, "config", "user.name", GH_USER], check=True)
    subprocess.run(["git", "-C", CLONE_DIR, "config", "user.email",
                    "ngthaitu12@gmail.com"], check=True)
    print("Da clone ->", CLONE_DIR)

if Path(CLONE_DIR, "ASSIGNMENT.md").exists():
    os.chdir(CLONE_DIR)

print("cwd =", os.getcwd())
print("Tim thay ASSIGNMENT.md:", Path("ASSIGNMENT.md").exists())

Da clone -> /content/lab19
cwd = /content/lab19
Tim thay ASSIGNMENT.md: True

In [12]:
import os, re, json, time, random, hashlib, unicodedata
from pathlib import Path
from collections import defaultdict, Counter, deque
from difflib import SequenceMatcher

import numpy as np
import pandas as pd
from tqdm.auto import tqdm
from neo4j import GraphDatabase



from sentence_transformers import SentenceTransformer
import faiss

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
pd.set_option("display.max_colwidth", 120)

def _load_dotenv():
    """Nap .env vao os.environ (chay ngoai Colab). Khong ghi de bien da ton tai."""
    for cand in [Path.cwd(), *Path.cwd().parents]:
        f = cand / ".env"
        if f.exists():
            for line in f.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, v = line.split("=", 1)
                os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))
            return f
    return None

_DOTENV = _load_dotenv()

def get_secret(name, default=None):
    try:
        from google.colab import userdata
        value = userdata.get(name)
        if value is not None:
            return value.strip() if isinstance(value, str) else value
    except Exception:
        pass
    v = os.environ.get(name, default)
    return v.strip() if isinstance(v, str) else v

NEO4J_URI = get_secret("NEO4J_URI", "")
NEO4J_USER = get_secret("NEO4J_USER", "neo4j")
NEO4J_PASSWORD = get_secret("NEO4J_PASSWORD", "")
NEO4J_DATABASE = get_secret("NEO4J_DATABASE", "neo4j")

GROQ_API_KEY = get_secret("GROQ_API_KEY", "")
GROQ_MODEL = get_secret("GROQ_MODEL", "")

JUDGE_PROVIDER = get_secret("JUDGE_PROVIDER", "openai").lower()
JUDGE_MODEL = get_secret("JUDGE_MODEL", "")
OPENAI_API_KEY = get_secret("OPENAI_API_KEY", "")
HF_TOKEN = get_secret("HF_TOKEN", "")

def _detect_repo():
    for p in [Path.cwd(), *Path.cwd().parents]:
        if (p / "ASSIGNMENT.md").exists():
            return p
    return Path.cwd()

REPO = _detect_repo()
for _d in ["data", "outputs", "reports"]:
    (REPO / _d).mkdir(parents=True, exist_ok=True)
print("REPO :", REPO)
print(".env :", _DOTENV)

DATA_PATH   = str(REPO / "data" / "hackernoon_subset.csv")
GOLDEN_PATH = str(REPO / "data" / "golden_dataset.csv")
OUTPUTS_DIR = REPO / "outputs"
REPORTS_DIR = REPO / "reports"
LAB_MAX_ARTICLES = 1500
LAB_MAX_CHUNKS = 3000
EXTRACTION_MAX_CHUNKS = 400
CHUNK_WORDS = 220
CHUNK_OVERLAP_WORDS = 40

# Nghi giua cac batch LLM de tranh rate-limit Groq free tier (~30 RPM).
LLM_BATCH_SLEEP = 8.0

_secrets = {
    "NEO4J_URI": NEO4J_URI,
    "NEO4J_PASSWORD": NEO4J_PASSWORD,
    "GROQ_API_KEY": GROQ_API_KEY,
    "GROQ_MODEL": GROQ_MODEL,
    "HF_TOKEN": HF_TOKEN,
    "JUDGE_MODEL": JUDGE_MODEL,
}
if JUDGE_PROVIDER == "openai":
    _secrets["OPENAI_API_KEY"] = OPENAI_API_KEY
for _k, _v in _secrets.items():
    print(f"{_k:<16}: {'OK' if _v else 'MISSING'}")
assert all(_secrets.values()), "Thieu secret. Kiem tra .env hoac Colab Secrets truoc khi chay tiep."

REPO : /content/lab19
.env : None
NEO4J_URI       : OK
NEO4J_PASSWORD  : OK
GROQ_API_KEY    : OK
GROQ_MODEL      : OK
HF_TOKEN        : OK
JUDGE_MODEL     : OK

In [19]:
try:
    obj, usage = groq_json(
        "Return strict JSON only.",
        'Return {"status": "ok"}'
    )
    print("THANH CONG:", obj)
    print("USAGE:", usage)
except Exception as e:
    print("LOI THUC SU:", repr(e))

THANH CONG: {'status': 'ok'}
USAGE: {'prompt_tokens': 114, 'completion_tokens': 73, 'total_tokens': 187}

## 1.3 — Download HackerNoon Dataset bằng Hugging Face Streaming

Cell dưới đây stream trực tiếp dataset **`HackerNoon/tech-company-news-data-dump`** và ghi dần ra CSV, nên không cần tải toàn bộ dataset vào RAM.

### Hai cơ chế giới hạn

- `LIMIT_ROWS`: số dòng tối đa.
- `LIMIT_MB`: dung lượng file tối đa.
- `PRIORITIZE_MB = True`: ưu tiên dừng theo dung lượng MB.
- `PRIORITIZE_MB = False`: thanh tiến trình theo số dòng, nhưng **vẫn giữ hard-stop `LIMIT_ROWS`**.

### Lưu ý

- Đặt `HF_TOKEN` trong **Colab Secrets**, không hard-code token vào notebook.
- Nếu dataset yêu cầu quyền truy cập/gated access, hãy mở trang dataset trên Hugging Face và hoàn tất bước **Agree/Request access** trước.
- Sau khi cell hoàn tất, `DATA_PATH` mặc định đã trỏ tới `/content/hackernoon_subset.csv`, nên cell loader kế tiếp có thể chạy trực tiếp.

In [5]:
#@title 1.3 — Stream HackerNoon dataset -> CSV
import csv
import os
from datasets import load_dataset
from tqdm.auto import tqdm

DATASET_NAME = "HackerNoon/tech-company-news-data-dump"
OUTPUT_CSV = DATA_PATH  # = REPO/data/hackernoon_subset.csv (da gitignore)

# Giới hạn cho bản lab. Có thể tăng sau buổi học.
LIMIT_ROWS = 1_000_000
LIMIT_MB = 300

# True  -> progress/dừng ưu tiên theo MB
# False -> progress theo rows; vẫn có hard-stop LIMIT_ROWS
PRIORITIZE_MB = True

# Đọc từ Colab Secrets qua get_secret() ở cell config.
if not HF_TOKEN:
    raise ValueError(
        "Thiếu HF_TOKEN. Hãy thêm Hugging Face Access Token vào Colab Secrets với tên HF_TOKEN."
    )

print("Đang kết nối luồng dữ liệu (streaming)...")

try:
    dataset = load_dataset(
        DATASET_NAME,
        split="train",
        streaming=True,
        token=HF_TOKEN,
    )
    iterator = iter(dataset)

    first_row = next(iterator)
    headers = list(first_row.keys())

    print(f"Đang ghi dữ liệu vào: {OUTPUT_CSV}")

    rows_written = 0
    total_progress = LIMIT_MB if PRIORITIZE_MB else LIMIT_ROWS
    unit_progress = "MB" if PRIORITIZE_MB else "row"

    with open(OUTPUT_CSV, mode="w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=headers, extrasaction="ignore")
        writer.writeheader()
        writer.writerow(first_row)
        rows_written += 1

        # Flush để kích thước file phản ánh dữ liệu vừa ghi.
        f.flush()
        file_size_mb = os.path.getsize(OUTPUT_CSV) / (1024 * 1024)

        with tqdm(
            total=total_progress,
            desc=f"Đang tải ({unit_progress})",
            unit=unit_progress,
        ) as pbar:
            if PRIORITIZE_MB:
                pbar.n = min(file_size_mb, LIMIT_MB)
                pbar.refresh()
            else:
                pbar.update(1)

            for row in iterator:
                writer.writerow(row)
                rows_written += 1

                # Kiểm tra dung lượng định kỳ để giảm overhead I/O.
                # Khi gần LIMIT_MB, kiểm tra mỗi row để dừng sát ngưỡng hơn.
                should_check_size = (
                    PRIORITIZE_MB
                    and (
                        rows_written % 100 == 0
                        or file_size_mb >= LIMIT_MB * 0.95
                    )
                )

                if should_check_size:
                    f.flush()
                    file_size_mb = os.path.getsize(OUTPUT_CSV) / (1024 * 1024)
                    pbar.n = min(round(file_size_mb, 2), LIMIT_MB)
                    pbar.refresh()
                elif not PRIORITIZE_MB:
                    pbar.update(1)

                # Hard-stop theo MB nếu đang ưu tiên dung lượng.
                if PRIORITIZE_MB and file_size_mb >= LIMIT_MB:
                    print(
                        f"\n[DỪNG] Đã đạt giới hạn dung lượng: "
                        f"{file_size_mb:.2f} MB "
                        f"(Tổng: {rows_written:,} dòng)"
                    )
                    break

                # Hard-stop theo số dòng trong mọi chế độ.
                if rows_written >= LIMIT_ROWS:
                    f.flush()
                    file_size_mb = os.path.getsize(OUTPUT_CSV) / (1024 * 1024)
                    print(
                        f"\n[DỪNG] Đã đạt giới hạn số dòng: "
                        f"{rows_written:,} dòng "
                        f"(Dung lượng: {file_size_mb:.2f} MB)"
                    )
                    break

        f.flush()

    final_size_mb = os.path.getsize(OUTPUT_CSV) / (1024 * 1024)
    print(
        f"✅ Hoàn thành: {os.path.abspath(OUTPUT_CSV)}\n"
        f"   Rows: {rows_written:,}\n"
        f"   Size: {final_size_mb:.2f} MB"
    )

    # Đồng bộ đường dẫn cho cell loader tiếp theo.
    DATA_PATH = OUTPUT_CSV

except StopIteration:
    raise RuntimeError("Dataset stream rỗng: không lấy được dòng đầu tiên.")
except Exception as e:
    print(f"\n❌ Có lỗi xảy ra: {e}")
    print(
        "Kiểm tra: (1) HF_TOKEN, (2) quyền Agree/Access trên Hugging Face, "
        "(3) kết nối mạng của Colab."
    )
    raise

Đang kết nối luồng dữ liệu (streaming)...

README.md: 0.00B [00:00, ?B/s]

Đang ghi dữ liệu vào: /content/lab19/data/hackernoon_subset.csv

Đang tải (MB):   0%|          | 0/300 [00:00<?, ?MB/s]

[DỪNG] Đã đạt giới hạn dung lượng: 300.00 MB (Tổng: 514,417 dòng)
✅ Hoàn thành: /content/lab19/data/hackernoon_subset.csv
   Rows: 514,417
   Size: 300.00 MB

In [6]:
#@title 1.4 — Neo4j connection + schema
driver = None

def connect_neo4j():
    global driver
    if not NEO4J_URI or not NEO4J_PASSWORD:
        raise ValueError("Thiếu Neo4j secrets.")
    driver = GraphDatabase.driver(
        NEO4J_URI,
        auth=(NEO4J_USER, NEO4J_PASSWORD),
    )
    driver.verify_connectivity()
    print("✅ Neo4j connected.")

def run_cypher(query, **params):
    if driver is None:
        raise RuntimeError("Hãy chạy connect_neo4j() trước.")
    with driver.session(database=NEO4J_DATABASE) as session:
        result = session.run(query, **params)
        rows = [r.data() for r in result]
        result.consume()
    return rows

def setup_graph_schema():
    for stmt in [
        """
        CREATE CONSTRAINT entity_id IF NOT EXISTS
        FOR (n:Entity) REQUIRE n.id IS UNIQUE
        """,
        """
        CREATE INDEX entity_name_norm IF NOT EXISTS
        FOR (n:Entity) ON (n.name_norm)
        """,
        """
        CREATE INDEX company_name_norm IF NOT EXISTS
        FOR (n:Company) ON (n.name_norm)
        """,
        """
        CREATE INDEX person_name_norm IF NOT EXISTS
        FOR (n:Person) ON (n.name_norm)
        """,
        """
        CREATE INDEX technology_name_norm IF NOT EXISTS
        FOR (n:Technology) ON (n.name_norm)
        """,
    ]:
        run_cypher(stmt)
    print("✅ Schema ready.")

connect_neo4j()
setup_graph_schema()

✅ Neo4j connected.
✅ Schema ready.

In [7]:
#@title 1.5 — Loader + exact dedup + chunking
def norm_space(x):
    return re.sub(r"\s+", " ", str(x or "")).strip()

def sha1(x):
    return hashlib.sha1(str(x).encode("utf-8", errors="ignore")).hexdigest()

def pick_col(df, candidates, required=True):
    lookup = {str(c).lower(): c for c in df.columns}
    for c in candidates:
        if c.lower() in lookup:
            return lookup[c.lower()]
    if required:
        raise KeyError(f"Missing one of columns: {candidates}")
    return None

def load_news(path):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(path)
    if path.suffix.lower() == ".csv":
        return pd.read_csv(path)
    if path.suffix.lower() in {".jsonl", ".ndjson"}:
        return pd.read_json(path, lines=True)
    if path.suffix.lower() == ".json":
        return pd.read_json(path)
    if path.suffix.lower() in {".parquet", ".pq"}:
        return pd.read_parquet(path)
    raise ValueError(f"Unsupported: {path.suffix}")

def standardize_news(raw):
    text_col = pick_col(raw, ["text", "content", "article", "body", "story", "description"])
    title_col = pick_col(raw, ["title", "headline"], required=False)
    date_col = pick_col(raw, ["published_date", "date", "published_at", "created_at"], required=False)
    id_col = pick_col(raw, ["id", "article_id", "story_id", "uuid"], required=False)

    df = pd.DataFrame()
    df["text"] = raw[text_col].fillna("").map(norm_space)
    df["title"] = raw[title_col].fillna("").map(norm_space) if title_col else ""

    if date_col:
        df["published_date"] = (
            pd.to_datetime(raw[date_col], errors="coerce", utc=True)
            .dt.strftime("%Y-%m-%d")
            .fillna("")
        )
    else:
        df["published_date"] = ""

    if id_col:
        df["article_id"] = raw[id_col].astype(str)
    else:
        df["article_id"] = [
            sha1(f"{t}\n{x}")[:20] for t, x in zip(df["title"], df["text"])
        ]

    df = df[df["text"].str.len() >= 80].copy()
    df["dedup_key"] = [
        sha1(norm_space(f"{t}\n{x}").lower())
        for t, x in zip(df["title"], df["text"])
    ]
    before = len(df)
    df = df.drop_duplicates("dedup_key").drop(columns="dedup_key").reset_index(drop=True)
    print(f"Exact dedup: {before:,} -> {len(df):,}")

    if LAB_MAX_ARTICLES and len(df) > LAB_MAX_ARTICLES:
        df = df.sample(LAB_MAX_ARTICLES, random_state=SEED).sort_index().reset_index(drop=True)
    return df

def chunk_text(text, size=220, overlap=40):
    words = norm_space(text).split()
    step = max(1, size - overlap)
    out = []
    for start in range(0, len(words), step):
        part = words[start:start+size]
        if not part:
            break
        out.append(" ".join(part))
        if start + size >= len(words):
            break
    return out

def build_chunks(news_df):
    rows = []
    for r in tqdm(news_df.itertuples(index=False), total=len(news_df), desc="Chunking"):
        for i, text in enumerate(chunk_text(r.text, CHUNK_WORDS, CHUNK_OVERLAP_WORDS)):
            rows.append({
                "chunk_id": f"{r.article_id}::c{i:04d}",
                "article_id": r.article_id,
                "title": r.title,
                "published_date": r.published_date,
                "text": text,
            })
            if LAB_MAX_CHUNKS and len(rows) >= LAB_MAX_CHUNKS:
                return pd.DataFrame(rows)
    return pd.DataFrame(rows)

raw_df = load_news(DATA_PATH)
news_df = standardize_news(raw_df)
chunks_df = build_chunks(news_df)
print(f"articles={len(news_df):,}  chunks={len(chunks_df):,}")
display(chunks_df.head())

Exact dedup: 245,324 -> 212,212

Chunking:   0%|          | 0/1500 [00:00<?, ?it/s]

articles=1,500  chunks=1,500

,chunk_id,article_id,title,published_date,text
0,d38fc817b7dc3eeeb535::c0000,d38fc817b7dc3eeeb535,Information Services Corporation Non-GAAP EPS of C$0.51 revenue of C$53.3M,2023-08-03,To ensure this doesn’t happen in the future please enable Javascript and cookies in your browser. Is this happening ...
1,830dbc6ea3082bb64be0::c0000,830dbc6ea3082bb64be0,How GSA’s Technology Transformation Services is Harnessing Change in Tech Modernization,2023-05-24,One component of GSA in particular Technology Transformation Services carries much of this mission by using modern m...
2,8cbfe069b03305566d73::c0000,8cbfe069b03305566d73,Information Technology,2023-05-18,At the most recent Berkshire Hathaway Inc. (NYSE: BRK-B) investors conference in early May Warren Buffett offered so...
3,331537d8f978a369b442::c0000,331537d8f978a369b442,Ryan Specialty Signs Definitive Agreement To Acquire Socius Insurance,2023-05-23,Ryan Specialty (NYSE:RYAN) a leading international specialty insurance firm is pleased to announce that it has signe...
4,55a09cbc43c41ffb2dd9::c0000,55a09cbc43c41ffb2dd9,Transact Campus Partnership Lands Talkiatry Services on Campus Transact Apps,2023-09-05,The partnership will “provide students with access to quality psychiatric services and offers an accessible and affo...

### 🎯 AI Coding Agent Challenge A — Near Dedup
Exact hash không bắt được bài repost/near-duplicate.

Hãy dùng AI Agent thiết kế thêm **MinHash/LSH, SimHash hoặc embedding+ANN**.  
**Không chấp nhận** pairwise cosine `O(N²)` trên toàn dataset.

Trong báo cáo nêu:
1. threshold,
2. false positive,
3. cách audit cặp bị merge.

In [13]:
from openai import OpenAI
openai_client = OpenAI(
    api_key=get_secret("OPENROUTER_API_KEY", ""),
    base_url="https://openrouter.ai/api/v1",
)
OPENAI_MODEL = get_secret("OPENAI_MODEL", "openai/gpt-4o-mini")

try:
    r = openai_client.chat.completions.create(
        model=OPENAI_MODEL,
        messages=[{"role":"user","content":'Return {"status":"ok"} as JSON.'}],
        response_format={"type":"json_object"},
        temperature=0.0,
    )
    print("THANH CONG:", r.choices[0].message.content)
except Exception as e:
    print("LOI THUC SU:", repr(e))

THANH CONG: {"status":"ok"}

In [8]:
#@title 1.6 — LLM wrapper có retry + JSON parsing
from groq import Groq
groq_client = Groq(api_key=GROQ_API_KEY) if GROQ_API_KEY else None

def parse_json_object(text):
    text = str(text).strip()
    text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.I)
    text = re.sub(r"\s*```$", "", text)
    a, b = text.find("{"), text.rfind("}")
    if a < 0 or b <= a:
        raise ValueError("No JSON object found.")
    return json.loads(text[a:b+1])

def groq_chat(messages, model=None, json_mode=False, max_retries=6):
    if groq_client is None:
        raise RuntimeError("Thiếu GROQ_API_KEY.")
    model = model or GROQ_MODEL
    if not model:
        raise RuntimeError("Thiếu GROQ_MODEL.")

    last = None
    for attempt in range(max_retries):
        try:
            kwargs = {
                "model": model,
                "messages": messages,
                "temperature": 0.0,
            }
            if json_mode:
                kwargs["response_format"] = {"type": "json_object"}

            resp = groq_client.chat.completions.create(**kwargs)
            usage = {}
            if getattr(resp, "usage", None):
                usage = {
                    "prompt_tokens": getattr(resp.usage, "prompt_tokens", None),
                    "completion_tokens": getattr(resp.usage, "completion_tokens", None),
                    "total_tokens": getattr(resp.usage, "total_tokens", None),
                }
            return resp.choices[0].message.content, usage
        except Exception as e:
            last = e
            if attempt == max_retries - 1:
                break
            time.sleep(min(60, 3 * (2 ** attempt) + random.random()))
    raise RuntimeError(last)

def groq_json(system, user, model=None):
    text, usage = groq_chat(
        [{"role": "system", "content": system},
         {"role": "user", "content": user}],
        model=model,
        json_mode=True,
    )
    return parse_json_object(text), usage

## 1.7 — Coreference Resolution

Yêu cầu:
- chỉ resolve đại từ khi antecedent rõ trong cùng chunk,
- không invent fact,
- giữ nguyên số/ngày/ticker/product,
- ambiguity → giữ nguyên và log `unresolved_mentions`.

**Failure mode quan trọng:** false coreference → false edge.

In [9]:
#@title 1.7 — Coreference resolution theo batch
COREF_SYSTEM = """
You are a conservative coreference-resolution component for a knowledge-graph pipeline.
Resolve pronouns and generic references only when the antecedent is clearly supported in the same chunk.
Never invent facts. Preserve dates, numbers, tickers and product names.
Return strict JSON only.
""".strip()

def resolve_coref_batch(batch_df):
    payload = [{"chunk_id": r.chunk_id, "text": r.text}
               for r in batch_df.itertuples(index=False)]

    prompt = f"""
Resolve coreferences.

Return:
{{
  "items": [
    {{
      "chunk_id": "...",
      "resolved_text": "...",
      "unresolved_mentions": ["..."]
    }}
  ]
}}

INPUT:
{json.dumps(payload, ensure_ascii=False)}
""".strip()

    obj, usage = groq_json(COREF_SYSTEM, prompt)
    by_id = {x.get("chunk_id"): x for x in obj.get("items", [])}

    rows = []
    for r in batch_df.itertuples(index=False):
        item = by_id.get(r.chunk_id, {})
        rows.append({
            "chunk_id": r.chunk_id,
            "resolved_text": norm_space(item.get("resolved_text") or r.text),
            "unresolved_mentions": item.get("unresolved_mentions", []),
        })
    return pd.DataFrame(rows), usage

def run_coref(chunks_subset, batch_size=5):
    out = []
    for start in tqdm(range(0, len(chunks_subset), batch_size), desc="Coref"):
        batch = chunks_subset.iloc[start:start+batch_size]
        try:
            df, _ = resolve_coref_batch(batch)
        except Exception:
            df = pd.DataFrame({
                "chunk_id": batch["chunk_id"].tolist(),
                "resolved_text": batch["text"].tolist(),
                "unresolved_mentions": [["COREF_BATCH_FAILED"] for _ in range(len(batch))],
            })
        out.append(df)
        time.sleep(LLM_BATCH_SLEEP)
    return pd.concat(out, ignore_index=True)

extraction_source = chunks_df.head(EXTRACTION_MAX_CHUNKS).copy()
coref_df = run_coref(extraction_source)
extraction_source = extraction_source.merge(coref_df, on="chunk_id", how="left")

_failed = coref_df.unresolved_mentions.map(lambda x: "COREF_BATCH_FAILED" in list(x)).sum()
_changed = (extraction_source.text != extraction_source.resolved_text).sum()
print(f"coref: changed={_changed}/{len(extraction_source)}  batch_failed={_failed}")
assert _failed < 0.2 * len(coref_df), "Qua nhieu batch coref that bai -> nghi rate-limit, xem plan.md 5.1"

Coref:   0%|          | 0/80 [00:00<?, ?it/s]

coref: changed=185/400  batch_failed=30

In [21]:
cmp = extraction_source[extraction_source.text != extraction_source.resolved_text][["chunk_id","text","resolved_text","unresolved_mentions"]]
print("Tong so bi doi:", len(cmp))
for r in cmp.head(3).itertuples():
    print("="*80)
    print("CHUNK:", r.chunk_id)
    print("BEFORE:", r.text[:300])
    print("AFTER :", r.resolved_text[:300])

Tong so bi doi: 202
================================================================================
CHUNK: 8cbfe069b03305566d73::c0000
BEFORE: At the most recent Berkshire Hathaway Inc. (NYSE: BRK-B) investors conference in early May Warren Buffett offered some insights into his most recent buys and sells but more detail was released ...
AFTER : At the most recent Berkshire Hathaway Inc. (NYSE: BRK-B) investors conference in early May Warren Buffett offered some insights into Warren Buffett's most recent buys and sells but more detail was released ...
================================================================================
CHUNK: 331537d8f978a369b442::c0000
BEFORE: Ryan Specialty (NYSE:RYAN) a leading international specialty insurance firm is pleased to announce that it has signed a definitive agreement to acquire Socius Insurance Services ('"Socius'") a nation
AFTER : Ryan Specialty (NYSE:RYAN) a leading international specialty insurance firm is pleased to announce that Ryan Specialty has signed a definitive agreement to acquire Socius Insurance Services ('"Socius'") a nation
================================================================================
CHUNK: 55a09cbc43c41ffb2dd9::c0000
BEFORE: The partnership will “provide students with access to quality psychiatric services and offers an accessible and affordable mental health support system” Talkiatry said. Transact said it will provide partner institutions with a “full suite of ...
AFTER : The partnership will “provide students with access to quality psychiatric services and offers an accessible and affordable mental health support system” Talkiatry said. Transact said Transact will provide partner institutions with a “full suite of ...

# PHẦN 2 — TRIPLE EXTRACTION & NEO4J BULK INSERT (15–45')

## Graph schema
**Nodes:** `Company`, `Person`, `Technology` + base label `Entity`.

**Relations:** `ACQUIRED`, `DEVELOPED`, `INVESTED_IN`, `FOUNDED`, `WORKED_AT`, `PARTNERED_WITH`, `USES`, `LEADS`.

**Mỗi edge bắt buộc:** `source_chunk_id`, `published_date`; khuyến nghị thêm `evidence`, `confidence`.

> Relation type phải qua allowlist trước khi ghép vào Cypher.

In [10]:
#@title 2.1 — NER + RE extraction
ALLOWED_NODE_TYPES = {"Company", "Person", "Technology"}
ALLOWED_RELATIONS = {
    "ACQUIRED", "DEVELOPED", "INVESTED_IN", "FOUNDED",
    "WORKED_AT", "PARTNERED_WITH", "USES", "LEADS"
}

EXTRACT_SYSTEM = f"""
Extract a high-precision knowledge graph from tech-news text.
Allowed node types: {sorted(ALLOWED_NODE_TYPES)}
Allowed relations: {sorted(ALLOWED_RELATIONS)}
Use only explicitly supported facts. Prefer precision over recall.
Every relation needs short evidence. Return strict JSON only.
""".strip()

def extract_batch(batch_df):
    payload = [{
        "chunk_id": r.chunk_id,
        "published_date": r.published_date,
        "text": getattr(r, "resolved_text", None) or r.text,
    } for r in batch_df.itertuples(index=False)]

    prompt = f"""
Return:
{{
  "items": [
    {{
      "chunk_id": "...",
      "relations": [
        {{
          "source": "...",
          "source_type": "Company|Person|Technology",
          "relation": "ALLOWED_RELATION",
          "target": "...",
          "target_type": "Company|Person|Technology",
          "evidence": "...",
          "confidence": 0.0
        }}
      ]
    }}
  ]
}}

INPUT:
{json.dumps(payload, ensure_ascii=False)}
""".strip()
    return groq_json(EXTRACT_SYSTEM, prompt)

def run_extraction(source_df, batch_size=4):
    meta = source_df.set_index("chunk_id")["published_date"].to_dict()
    triples, errors = [], []

    for start in tqdm(range(0, len(source_df), batch_size), desc="NER+RE"):
        batch = source_df.iloc[start:start+batch_size]
        try:
            obj, _ = extract_batch(batch)
        except Exception as e:
            errors.append({"start": start, "error": str(e)})
            continue

        for item in obj.get("items", []):
            cid = item.get("chunk_id")
            if cid not in meta:
                continue
            for x in item.get("relations", []):
                s, t = norm_space(x.get("source")), norm_space(x.get("target"))
                st, tt, rel = x.get("source_type"), x.get("target_type"), x.get("relation")
                if not s or not t:
                    continue
                if st not in ALLOWED_NODE_TYPES or tt not in ALLOWED_NODE_TYPES:
                    continue
                if rel not in ALLOWED_RELATIONS:
                    continue
                triples.append({
                    "source_raw": s,
                    "source_type": st,
                    "relation": rel,
                    "target_raw": t,
                    "target_type": tt,
                    "source_chunk_id": cid,
                    "published_date": meta[cid] or "",
                    "evidence": norm_space(x.get("evidence")),
                    "confidence": float(x.get("confidence") or 0.0),
                })

        time.sleep(LLM_BATCH_SLEEP)

    return pd.DataFrame(triples), pd.DataFrame(errors)

raw_triples_df, extraction_errors_df = run_extraction(extraction_source)
print(f"triples={len(raw_triples_df):,}  errors={len(extraction_errors_df)}")
assert not raw_triples_df.empty, "Khong trich xuat duoc triple nao."
assert set(raw_triples_df.relation) <= ALLOWED_RELATIONS
assert set(raw_triples_df.source_type) | set(raw_triples_df.target_type) <= ALLOWED_NODE_TYPES
display(raw_triples_df.head())

NER+RE:   0%|          | 0/100 [00:00<?, ?it/s]

KeyboardInterrupt:

In [14]:
#@title 2.1 — NER + RE extraction (OpenRouter)
from openai import OpenAI
openai_client = OpenAI(
    api_key=get_secret("OPENROUTER_API_KEY", ""),
    base_url="https://openrouter.ai/api/v1",
)
OPENAI_MODEL = get_secret("OPENAI_MODEL", "openai/gpt-4o-mini")

def openai_chat(messages, model=None, json_mode=False, max_retries=4):
    if openai_client is None:
        raise RuntimeError("Thieu OPENROUTER_API_KEY.")
    model = model or OPENAI_MODEL
    last = None
    for attempt in range(max_retries):
        try:
            kwargs = {"model": model, "messages": messages, "temperature": 0.0}
            if json_mode:
                kwargs["response_format"] = {"type": "json_object"}
            resp = openai_client.chat.completions.create(**kwargs)
            usage = {}
            if getattr(resp, "usage", None):
                usage = {
                    "prompt_tokens": getattr(resp.usage, "prompt_tokens", None),
                    "completion_tokens": getattr(resp.usage, "completion_tokens", None),
                    "total_tokens": getattr(resp.usage, "total_tokens", None),
                }
            return resp.choices[0].message.content, usage
        except Exception as e:
            last = e
            if attempt == max_retries - 1:
                break
            time.sleep(min(30, 2 * (2 ** attempt) + random.random()))
    raise RuntimeError(last)

def openai_json(system, user, model=None):
    text, usage = openai_chat(
        [{"role": "system", "content": system}, {"role": "user", "content": user}],
        model=model, json_mode=True,
    )
    return parse_json_object(text), usage

ALLOWED_NODE_TYPES = {"Company", "Person", "Technology"}
ALLOWED_RELATIONS = {
    "ACQUIRED", "DEVELOPED", "INVESTED_IN", "FOUNDED",
    "WORKED_AT", "PARTNERED_WITH", "USES", "LEADS"
}

EXTRACT_SYSTEM = f"""
Extract a high-precision knowledge graph from tech-news text.
Allowed node types: {sorted(ALLOWED_NODE_TYPES)}
Allowed relations: {sorted(ALLOWED_RELATIONS)}
Use only explicitly supported facts. Prefer precision over recall.
Every relation needs short evidence. Return strict JSON only.
""".strip()

def extract_batch(batch_df):
    payload = [{
        "chunk_id": r.chunk_id, "published_date": r.published_date,
        "text": getattr(r, "resolved_text", None) or r.text,
    } for r in batch_df.itertuples(index=False)]
    prompt = f"""
Return:
{{
  "items": [
    {{
      "chunk_id": "...",
      "relations": [
        {{
          "source": "...", "source_type": "Company|Person|Technology",
          "relation": "ALLOWED_RELATION",
          "target": "...", "target_type": "Company|Person|Technology",
          "evidence": "...", "confidence": 0.0
        }}
      ]
    }}
  ]
}}

INPUT:
{json.dumps(payload, ensure_ascii=False)}
""".strip()
    return openai_json(EXTRACT_SYSTEM, prompt)

def run_extraction(source_df, batch_size=4):
    meta = source_df.set_index("chunk_id")["published_date"].to_dict()
    triples, errors = [], []
    for start in tqdm(range(0, len(source_df), batch_size), desc="NER+RE"):
        batch = source_df.iloc[start:start+batch_size]
        try:
            obj, _ = extract_batch(batch)
        except Exception as e:
            errors.append({"start": start, "error": str(e)}); continue
        for item in obj.get("items", []):
            cid = item.get("chunk_id")
            if cid not in meta: continue
            for x in item.get("relations", []):
                s, t = norm_space(x.get("source")), norm_space(x.get("target"))
                st, tt, rel = x.get("source_type"), x.get("target_type"), x.get("relation")
                if not s or not t: continue
                if st not in ALLOWED_NODE_TYPES or tt not in ALLOWED_NODE_TYPES: continue
                if rel not in ALLOWED_RELATIONS: continue
                triples.append({
                    "source_raw": s, "source_type": st, "relation": rel,
                    "target_raw": t, "target_type": tt,
                    "source_chunk_id": cid, "published_date": meta[cid] or "",
                    "evidence": norm_space(x.get("evidence")),
                    "confidence": float(x.get("confidence") or 0.0),
                })
        time.sleep(0.3)
    return pd.DataFrame(triples), pd.DataFrame(errors)

raw_triples_df, extraction_errors_df = run_extraction(extraction_source)
print(f"triples={len(raw_triples_df):,}  errors={len(extraction_errors_df)}")
assert not raw_triples_df.empty, "Khong trich xuat duoc triple nao."
assert set(raw_triples_df.relation) <= ALLOWED_RELATIONS
assert set(raw_triples_df.source_type) | set(raw_triples_df.target_type) <= ALLOWED_NODE_TYPES
display(raw_triples_df.head())

NER+RE:   0%|          | 0/100 [00:00<?, ?it/s]

triples=121  errors=0

,source_raw,source_type,relation,target_raw,target_type,source_chunk_id,published_date,evidence,confidence
0,Ryan Specialty,Company,ACQUIRED,Socius Insurance Services,Company,331537d8f978a369b442::c0000,2023-05-23,Ryan Specialty has signed a definitive agreement to acquire Socius Insurance Services,1.0
1,Synchron,Company,DEVELOPED,brain-computer interface technology,Technology,a7a8a5531a30bc5c7fbb::c0000,2023-02-18,Synchron is part of an emerging crop of companies testing technology in the brain-computer interface industry.,0.9
2,Sensormatic Solutions,Company,PARTNERED_WITH,Zliide,Company,adb56add69f473fc4105::c0000,2023-01-16,Sensormatic Solutions' collaboration with Zliide a technology company.,0.8
3,ServiceNow Inc.,Company,DEVELOPED,Now platform,Technology,3a1191cd49142548e77e::c0000,2023-03-22,ServiceNow Inc. is rolling out a new version of ServiceNow Inc.'s Now platform that features several artificial inte...,1.0
4,UJET,Company,PARTNERED_WITH,Google Cloud,Company,2512bf46ee71633efb09::c0000,2023-08-29,UJET announced a relationship with Google Cloud as a strategic technology partner,1.0

In [27]:
try:
    obj, usage = groq_json(
        "Return strict JSON only.",
        'Return {"status": "ok"}'
    )
    print("THANH CONG:", obj)
except Exception as e:
    print("LOI THUC SU:", repr(e))

THANH CONG: {'status': 'ok'}

In [23]:
import re

# Uu tien chunk co >=2 ten cong ty/thuc the viet hoa gan nhau (rui ro nham antecedent cao)
def count_capitalized_seqs(text):
    return len(re.findall(r'\b[A-Z][a-zA-Z&\.]*(?:\s[A-Z][a-zA-Z&\.]*){0,2}\b', text))

cmp2 = extraction_source[extraction_source.text != extraction_source.resolved_text].copy()
cmp2["risk_score"] = cmp2.text.map(count_capitalized_seqs)
risky = cmp2.sort_values("risk_score", ascending=False).head(6)
for r in risky.itertuples():
    print("="*80)
    print("CHUNK:", r.chunk_id, "| risk_score:", r.risk_score)
    print("BEFORE:", r.text[:350])
    print("AFTER :", r.resolved_text[:350])

print("\n" + "#"*80)
print("VI DU unresolved_mentions (co ghi nhan, khong tu suy dien):")
unresolved = extraction_source[extraction_source.unresolved_mentions.map(len) > 0]
print("Tong so:", len(unresolved))
for r in unresolved.head(3).itertuples():
    print("-"*80)
    print("CHUNK:", r.chunk_id)
    print("TEXT:", r.text[:250])
    print("UNRESOLVED:", r.unresolved_mentions)

================================================================================
CHUNK: fa44e0ddb529ef9fc5c9::c0000 | risk_score: 12
BEFORE: Dar Al-Handasah Consultants – Dar – inaugurated its new Poland office at Aleje Jerozolimskie 142 B 02-305 Warsaw. The move comes after the company began its design activities as the Master Civil Engineer on Poland’s new Centralny Port Komunikacyjny (CPK) Airport.
AFTER : Dar Al-Handasah Consultants – Dar – inaugurated Dar Al-Handasah Consultants – Dar’s new Poland office at Aleje Jerozolimskie 142 B 02-305 Warsaw. The move comes after Dar Al-Handasah Consultants – Dar began Dar Al-Handasah Consultants – Dar’s design activities as the Master Civil Engineer on Poland’s new Centralny Port Komunikacyjny (CPK) Airport.
================================================================================
CHUNK: 3b88e0a6901a058b025a::c0000 | risk_score: 11
BEFORE: After opening 2-0 and getting a day off the USA men resume Volleyball Nations League play Saturday when they face Canada at 8 p.m. Eastern. The USA swept the Netherlands and Italy while Canada beat Cuba in five before losing to Argentina in four.
AFTER : After opening 2-0 and getting a day off the USA men resume Volleyball Nations League play Saturday when the USA men face Canada at 8 p.m. Eastern. The USA swept the Netherlands and Italy while Canada beat Cuba in five before losing to Argentina in four.
================================================================================
CHUNK: 77f7018d6b3f8b793992::c0000 | risk_score: 11
BEFORE: Analysis: There’s No Substitute for Chinese Drones (and That’s a Problem) Create an FP account to save articles to read later and in the FP mobile app. Sign Up ALREADY AN FP SUBSCRIBER?
AFTER : Analysis: There’s No Substitute for Chinese Drones (and The lack of substitute for Chinese Drones is a Problem) Create an FP account to save articles to read later and in the FP mobile app. Sign Up ALREADY AN FP SUBSCRIBER?
================================================================================
CHUNK: f2b9614df809bba2ab72::c0000 | risk_score: 11
BEFORE: CNN is planning another Independence Day special The Fourth In America that will include performances from Post Malone Demi Lovato Zac Brown Band and Leon Bridges. Dana Bash Boris Sanchez Victor Blackwell and Cari Champion will host the special
AFTER : CNN is planning another Independence Day special The Fourth In America that will include performances from Post Malone Demi Lovato Zac Brown Band and Leon Bridges. Dana Bash Boris Sanchez Victor Blackwell and Cari Champion will host the Independence Day special The Fourth In America
================================================================================
CHUNK: 69f2aecea98a9294feb6::c0000 | risk_score: 10
BEFORE: Governor Mohammed Umar Bago of Niger State has directed the payment of N900 million as a counterpart fund for the World Bank’s Agro-Climatic Resilience in Semi-Arid Landscapes (ACReSAL) project. He issued this directive during the launch of the ...
AFTER : Governor Mohammed Umar Bago of Niger State has directed the payment of N900 million as a counterpart fund for the World Bank’s Agro-Climatic Resilience in Semi-Arid Landscapes (ACReSAL) project. Governor Mohammed Umar Bago issued this directive during the launch of the ...
================================================================================
CHUNK: 7c7af186346d75b51afd::c0000 | risk_score: 10
BEFORE: US technology company NVIDIA and billionaire Mukesh Ambani''s Reliance Industries on Friday announced a partnership to build AI supercomputers in India. ''''The companies will work together to build AI infrastructure that is over an order of magnitude more powerful than the fastest supercomputer in India today'''' the firms said in a statement.
AFTER : US technology company NVIDIA and billionaire Mukesh Ambani''s Reliance Industries on Friday announced a partnership to build AI supercomputers in India. ''''NVIDIA and Reliance Industries will work together to build AI infrastructure that is over an order of magnitude more powerful than the fastest supercomputer in India today'''' NVIDIA and Relian

################################################################################
VI DU unresolved_mentions (co ghi nhan, khong tu suy dien):
Tong so: 77
--------------------------------------------------------------------------------
CHUNK: d38fc817b7dc3eeeb535::c0000
TEXT: To ensure this doesn’t happen in the future please enable Javascript and cookies in your browser. Is this happening to you frequently? Please report it on our ...
UNRESOLVED: ['this', 'you', 'it']
--------------------------------------------------------------------------------
CHUNK: 830dbc6ea3082bb64be0::c0000
TEXT: One component of GSA in particular Technology Transformation Services carries much of this mission by using modern methodologies and technologies to improve the public’s experience with the ...
UNRESOLVED: ['this mission']
--------------------------------------------------------------------------------
CHUNK: 5d1df43703396c12c3c2::c0000
TEXT: That is until defense contractor Lockheed noticed it and had his works translated into English; Ufimtsev’s work became the basis for modern-day stealth technology ... replace the B-1 and B-2 in Air Force service. US Air Force Stealth was the great ..
UNRESOLVED: ['it', 'his']

## 2.2 — Entity Resolution bằng Vector Similarity

Pipeline:
1. Manual aliases cho ticker/tên rất phổ biến.
2. Embedding ANN candidate.
3. Lexical guard để giảm false merge.
4. Xuất audit table.

### 🎯 AI Coding Agent Challenge B
Cải tiến guard cho:
- ticker,
- suffix `Inc./Corp./Ltd.`,
- product chứa company name,
- người trùng họ/tên gần giống.

In [15]:
#@title 2.2 — Entity resolution
CORP_SUFFIXES = {"inc","incorporated","corp","corporation","ltd","limited","llc","plc","co","company"}
MANUAL_ALIASES = {
    "msft": "Microsoft",
    "microsoft corp": "Microsoft",
    "microsoft corporation": "Microsoft",
    "goog": "Google",
    "googl": "Google",
    "google llc": "Google",
    "meta platforms": "Meta",
    "meta platforms inc": "Meta",
    "aapl": "Apple",
    "apple inc": "Apple",
}

def norm_entity(name):
    s = unicodedata.normalize("NFKC", norm_space(name)).lower()
    s = re.sub(r"[^\w\s\-\.]", " ", s)
    return re.sub(r"\s+", " ", s).strip()

def strip_suffix(name):
    toks = norm_entity(name).replace(".", "").split()
    while toks and toks[-1] in CORP_SUFFIXES:
        toks.pop()
    return " ".join(toks)

def merge_guard(a, b):
    na, nb = strip_suffix(a), strip_suffix(b)
    if na == nb:
        return True
    return SequenceMatcher(None, na, nb).ratio() >= 0.72

EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
embedder = None

def get_embedder():
    global embedder
    if embedder is None:
        embedder = SentenceTransformer(EMBED_MODEL)
    return embedder

class UF:
    def __init__(self, n):
        self.p = list(range(n))
    def find(self, x):
        if self.p[x] != x:
            self.p[x] = self.find(self.p[x])
        return self.p[x]
    def union(self, a, b):
        a, b = self.find(a), self.find(b)
        if a != b:
            self.p[b] = a

def build_resolution_map(raw_triples_df, threshold=0.90, top_k=5):
    mentions = []
    for r in raw_triples_df.itertuples(index=False):
        mentions += [(r.source_type, r.source_raw), (r.target_type, r.target_raw)]

    counts = Counter((t, norm_entity(n)) for t, n in mentions)
    display_name = {}
    for t, n in mentions:
        display_name.setdefault((t, norm_entity(n)), n)

    mapping, audit = {}, []

    for key in counts:
        t, norm = key
        if norm in MANUAL_ALIASES:
            mapping[key] = MANUAL_ALIASES[norm]
            audit.append({
                "type": t, "left": display_name[key],
                "right": MANUAL_ALIASES[norm],
                "similarity": 1.0, "decision": "MERGE_MANUAL"
            })

    for typ in sorted(ALLOWED_NODE_TYPES):
        keys = [k for k in counts if k[0] == typ and k not in mapping]
        if not keys:
            continue
        names = [display_name[k] for k in keys]
        vecs = get_embedder().encode(
            names, batch_size=128, show_progress_bar=False,
            normalize_embeddings=True
        ).astype("float32")

        index = faiss.IndexFlatIP(vecs.shape[1])
        index.add(vecs)
        sims, nbrs = index.search(vecs, min(top_k, len(names)))
        uf = UF(len(names))

        for i in range(len(names)):
            for score, j in zip(sims[i], nbrs[i]):
                if j < 0 or i >= j or float(score) < threshold:
                    continue
                ok = merge_guard(names[i], names[j])
                audit.append({
                    "type": typ, "left": names[i], "right": names[j],
                    "similarity": float(score),
                    "decision": "MERGE_VECTOR" if ok else "REJECT_GUARD"
                })
                if ok:
                    uf.union(i, j)

        groups = defaultdict(list)
        for i in range(len(names)):
            groups[uf.find(i)].append(i)

        for idxs in groups.values():
            best = sorted(
                idxs,
                key=lambda i: (-counts[keys[i]], len(names[i]), names[i].lower())
            )[0]
            canonical = names[best]
            for i in idxs:
                mapping[keys[i]] = canonical

    for key in counts:
        mapping.setdefault(key, display_name[key])

    return mapping, pd.DataFrame(audit)

def canonicalize_triples(raw_df, mapping):
    df = raw_df.copy()
    def canon(name, typ):
        n = norm_entity(name)
        return mapping.get((typ, n), MANUAL_ALIASES.get(n, name))

    df["source_name"] = [canon(n,t) for n,t in zip(df.source_raw, df.source_type)]
    df["target_name"] = [canon(n,t) for n,t in zip(df.target_raw, df.target_type)]
    df["source_name_norm"] = df.source_name.map(norm_entity)
    df["target_name_norm"] = df.target_name.map(norm_entity)
    df["source_id"] = [sha1(f"{t}:{n}")[:24] for t,n in zip(df.source_type, df.source_name_norm)]
    df["target_id"] = [sha1(f"{t}:{n}")[:24] for t,n in zip(df.target_type, df.target_name_norm)]
    return df[df.source_id != df.target_id].reset_index(drop=True)

# threshold=0.85 (thay vi 0.90): mo rong recall cua candidate generation,
# day ganh nang chong false-merge sang Lexical Guard. Xem plan.md muc M3.
ER_THRESHOLD = 0.85
ER_TOP_K = 8

entity_map, entity_resolution_audit_df = build_resolution_map(
    raw_triples_df, threshold=ER_THRESHOLD, top_k=ER_TOP_K
)
triples_df = canonicalize_triples(raw_triples_df, entity_map)

print(f"audit rows = {len(entity_resolution_audit_df)}")
print(entity_resolution_audit_df.decision.value_counts().to_string())
entity_resolution_audit_df.to_csv(OUTPUTS_DIR / "entity_resolution_audit.csv", index=False)
display(entity_resolution_audit_df.sort_values("similarity", ascending=False).head(20))

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

audit rows = 4
decision
MERGE_VECTOR    4

,type,left,right,similarity,decision
0,Company,Reliance Industries Ltd,Reliance Industries,0.944749,MERGE_VECTOR
1,Company,Activision Blizzard,Activision Blizzard Inc.,0.918492,MERGE_VECTOR
2,Company,Airbnb,Airbnb Inc.,0.874692,MERGE_VECTOR
3,Technology,Chandrayaan-I,Chandrayaan-III,0.858351,MERGE_VECTOR

In [16]:
#@title 2.3 — Node table + UNWIND bulk insert
def build_nodes(triples_df):
    rows = []
    for r in triples_df.itertuples(index=False):
        rows += [
            {"id":r.source_id,"name":r.source_name,"name_norm":r.source_name_norm,"type":r.source_type,"alias":r.source_raw},
            {"id":r.target_id,"name":r.target_name,"name_norm":r.target_name_norm,"type":r.target_type,"alias":r.target_raw},
        ]
    tmp = pd.DataFrame(rows)
    if tmp.empty:
        return tmp

    out = []
    for (node_id,name,name_norm,typ), g in tmp.groupby(["id","name","name_norm","type"]):
        aliases = sorted(set(g["alias"].map(norm_space)))
        out.append({
            "id":node_id, "name":name, "name_norm":name_norm, "type":typ,
            "aliases":aliases,
            "aliases_norm":sorted(set(norm_entity(x) for x in aliases))
        })
    return pd.DataFrame(out)

def batches(records, size=1000):
    for i in range(0, len(records), size):
        yield records[i:i+size]

def bulk_insert_nodes(nodes_df, batch_size=1000):
    for typ in sorted(ALLOWED_NODE_TYPES):
        part = nodes_df[nodes_df.type == typ]
        if part.empty:
            continue
        query = f"""
        UNWIND $rows AS row
        MERGE (n:Entity {{id: row.id}})
        SET n:{typ},
            n.name=row.name,
            n.name_norm=row.name_norm,
            n.entity_type=row.type,
            n.aliases=row.aliases,
            n.aliases_norm=row.aliases_norm
        """
        for b in batches(part.to_dict("records"), batch_size):
            run_cypher(query, rows=b)

def bulk_insert_edges(triples_df, batch_size=1000):
    required = {"source_chunk_id","published_date"}
    if not required.issubset(triples_df.columns):
        raise ValueError("Missing edge provenance.")

    for rel in sorted(ALLOWED_RELATIONS):
        part = triples_df[triples_df.relation == rel]
        if part.empty:
            continue

        query = f"""
        UNWIND $rows AS row
        MATCH (s:Entity {{id: row.source_id}})
        MATCH (t:Entity {{id: row.target_id}})
        MERGE (s)-[r:{rel} {{source_chunk_id: row.source_chunk_id}}]->(t)
        SET r.published_date=row.published_date,
            r.evidence=row.evidence,
            r.confidence=row.confidence
        """

        cols = ["source_id","target_id","source_chunk_id","published_date","evidence","confidence"]
        for b in batches(part[cols].to_dict("records"), batch_size):
            run_cypher(query, rows=b)

nodes_df = build_nodes(triples_df)
bulk_insert_nodes(nodes_df)
bulk_insert_edges(triples_df)
print(f"nodes={len(nodes_df):,}  edges={len(triples_df):,} -> da nap vao Neo4j")

nodes=197  edges=120 -> da nap vao Neo4j

In [17]:
#@title 2.4 — Sanity checks
def graph_checks():
    invalid = run_cypher("""
    MATCH ()-[r]->()
    WHERE r.source_chunk_id IS NULL OR r.published_date IS NULL
    RETURN count(r) AS n
    """)[0]["n"]

    counts = {
        "nodes": run_cypher("MATCH (n:Entity) RETURN count(n) AS n")[0]["n"],
        "edges": run_cypher("MATCH ()-[r]->() RETURN count(r) AS n")[0]["n"],
        "invalid_provenance_edges": invalid,
    }
    print(counts)
    assert invalid == 0

    top = pd.DataFrame(run_cypher("""
    MATCH (n:Entity)
    OPTIONAL MATCH (n)-[r]-()
    WITH n, count(r) AS degree
    RETURN n.id AS id, n.name AS name, n.entity_type AS type, degree
    ORDER BY degree DESC LIMIT 15
    """))
    display(top)
    return counts, top

graph_counts, top_degree_df = graph_checks()

{'nodes': 197, 'edges': 119, 'invalid_provenance_edges': 0}

,id,name,type,degree
0,a1db046fa1cf05904c8cb3a8,Reliance Industries,Company,6
1,7b219357277193c25d37d788,Railergy,Company,5
2,1f2054ff9fad32685f6dda3b,Norwegian University of Life Sciences,Company,4
3,b0f073fc691ac6ea5bfa2c41,Activision Blizzard,Company,4
4,b823fb02e58a12bdc4c38934,NVIDIA,Company,3
5,c2fcf23ba561589b0b1df4ba,US revenues,Technology,3
6,5b619ed690d75481907e2863,Airbnb,Company,3
7,269d5bc0969e0b170f016315,Aaritya Technologies,Company,3
8,8693b055457df450df9cfcdf,Unacademy,Company,3
9,a5ecbacff981ced8953c6ce0,ATOSS Software,Company,2
10,95fdfcdea30320fbcd96b512,A-Mark Precious Metals,Company,2
11,8cc9b1d6d7b00f4190f13dd0,Andreessen Horowitz,Company,2
12,74bd8cb542da5b4c9e6e42ad,Dar Al-Handasah Consultants,Company,2
13,6979b0d4a71ab90434659ac6,Indian Space Research Organisation,Company,2
14,39430d6a0c7aa28d8fe56bf3,Meeno,Company,2

# PHẦN 3 — FLAT RAG & HYBRID GRAPHRAG (45–75')

## Flat RAG baseline
Dùng cùng embedding/generator để comparison tập trung vào retrieval architecture.

In [19]:
#@title 3.2 — Seed matching
SEED_SYSTEM = """
Extract useful seed entities for graph retrieval.
Allowed types: Company, Person, Technology.
Do not answer the question. Return strict JSON only.
""".strip()

def extract_seeds(query):
    obj, _ = openai_json(SEED_SYSTEM, f"""
Question: {query}
Return {{"seeds":[{{"name":"...","type":"Company|Person|Technology|null"}}]}}
""")
    return [
        {"name":norm_space(x.get("name")),
         "type":x.get("type") if x.get("type") in ALLOWED_NODE_TYPES else None}
        for x in obj.get("seeds", [])
        if norm_space(x.get("name"))
    ]

def build_entity_matcher(nodes_df):
    global entity_match_vectors, entity_match_store
    entity_match_store = nodes_df.reset_index(drop=True).copy()
    entity_match_vectors = get_embedder().encode(
        entity_match_store.name.tolist(),
        batch_size=128, show_progress_bar=False,
        normalize_embeddings=True
    ).astype("float32")

def match_seeds(query, fuzzy_threshold=0.66):
    matched = []
    for seed in extract_seeds(query):
        exact = run_cypher("""
        MATCH (n:Entity)
        WHERE (n.name_norm=$name OR $name IN coalesce(n.aliases_norm,[]))
          AND ($typ IS NULL OR n.entity_type=$typ)
        RETURN n.id AS id, n.name AS name, n.entity_type AS type
        LIMIT 5
        """, name=norm_entity(seed["name"]), typ=seed["type"])
        if exact:
            matched += exact
            continue
        if entity_match_vectors is None:
            continue
        mask = np.ones(len(entity_match_store), dtype=bool)
        if seed["type"]:
            mask = entity_match_store.type.eq(seed["type"]).to_numpy()
        idxs = np.flatnonzero(mask)
        if not len(idxs):
            continue
        qv = get_embedder().encode(
            [seed["name"]], normalize_embeddings=True, show_progress_bar=False
        ).astype("float32")[0]
        sims = entity_match_vectors[idxs] @ qv
        j = int(np.argmax(sims))
        if float(sims[j]) >= fuzzy_threshold:
            r = entity_match_store.iloc[int(idxs[j])]
            matched.append({"id":r.id,"name":r.name,"type":r.type})
    return list({x["id"]: x for x in matched}.values())

build_entity_matcher(nodes_df)

In [18]:
#@title 3.1 — Flat RAG
flat_index = None
flat_store = None
entity_match_vectors = None
entity_match_store = None

def build_flat_index(chunks_df):
    global flat_index, flat_store
    vecs = get_embedder().encode(
        chunks_df.text.fillna("").tolist(),
        batch_size=128, show_progress_bar=True,
        normalize_embeddings=True
    ).astype("float32")

    flat_index = faiss.IndexFlatIP(vecs.shape[1])
    flat_index.add(vecs)
    flat_store = chunks_df.reset_index(drop=True).copy()
    print("Flat vectors:", flat_index.ntotal)

def retrieve_flat_context(query, k=6):
    qv = get_embedder().encode(
        [query], normalize_embeddings=True, show_progress_bar=False
    ).astype("float32")
    scores, ids = flat_index.search(qv, min(k, flat_index.ntotal))

    rows = []
    for score, idx in zip(scores[0], ids[0]):
        if idx < 0:
            continue
        r = flat_store.iloc[int(idx)]
        rows.append({
            "score":float(score), "chunk_id":r.chunk_id,
            "published_date":r.published_date, "text":r.text
        })

    df = pd.DataFrame(rows)
    context = "\n\n".join(
        f"[chunk_id={r.chunk_id} | date={r.published_date} | score={r.score:.3f}]\n{r.text}"
        for r in df.itertuples(index=False)
    )
    return context, df

build_flat_index(chunks_df)

Batches:   0%|          | 0/12 [00:00<?, ?it/s]

Flat vectors: 1500

## Graph retrieval flow
1. LLM trích seed entities.
2. Match seed trong Neo4j; fuzzy fallback bằng embedding.
3. BFS tối đa `max_hops`.
4. Nếu node degree > 100 → chỉ lấy tối đa 50 edge mới nhất.
5. Global edge cap để tránh context explosion.
6. Textualize subgraph có provenance.

In [ ]:
#@title 3.2 — Seed matching
SEED_SYSTEM = """
Extract useful seed entities for graph retrieval.
Allowed types: Company, Person, Technology.
Do not answer the question. Return strict JSON only.
""".strip()

def extract_seeds(query):
    obj, _ = groq_json(SEED_SYSTEM, f"""
Question: {query}
Return {{"seeds":[{{"name":"...","type":"Company|Person|Technology|null"}}]}}
""")
    return [
        {"name":norm_space(x.get("name")),
         "type":x.get("type") if x.get("type") in ALLOWED_NODE_TYPES else None}
        for x in obj.get("seeds", [])
        if norm_space(x.get("name"))
    ]

def build_entity_matcher(nodes_df):
    global entity_match_vectors, entity_match_store
    entity_match_store = nodes_df.reset_index(drop=True).copy()
    entity_match_vectors = get_embedder().encode(
        entity_match_store.name.tolist(),
        batch_size=128, show_progress_bar=False,
        normalize_embeddings=True
    ).astype("float32")

def match_seeds(query, fuzzy_threshold=0.66):
    matched = []
    for seed in extract_seeds(query):
        exact = run_cypher("""
        MATCH (n:Entity)
        WHERE (n.name_norm=$name OR $name IN coalesce(n.aliases_norm,[]))
          AND ($typ IS NULL OR n.entity_type=$typ)
        RETURN n.id AS id, n.name AS name, n.entity_type AS type
        LIMIT 5
        """, name=norm_entity(seed["name"]), typ=seed["type"])

        if exact:
            matched += exact
            continue

        if entity_match_vectors is None:
            continue

        mask = np.ones(len(entity_match_store), dtype=bool)
        if seed["type"]:
            mask = entity_match_store.type.eq(seed["type"]).to_numpy()
        idxs = np.flatnonzero(mask)
        if not len(idxs):
            continue

        qv = get_embedder().encode(
            [seed["name"]], normalize_embeddings=True, show_progress_bar=False
        ).astype("float32")[0]
        sims = entity_match_vectors[idxs] @ qv
        j = int(np.argmax(sims))
        if float(sims[j]) >= fuzzy_threshold:
            r = entity_match_store.iloc[int(idxs[j])]
            matched.append({"id":r.id,"name":r.name,"type":r.type})

    return list({x["id"]: x for x in matched}.values())

build_entity_matcher(nodes_df)

In [20]:
#@title 3.3 — Graph traversal + super-node mitigation
SUPER_NODE_DEGREE = 100
SUPER_NODE_EDGE_CAP = 50
GLOBAL_EDGE_CAP = 250
MAX_GRAPH_CONTEXT_CHARS = 14000

def node_degree(node_id):
    return int(run_cypher("""
    MATCH (n:Entity {id:$id})
    OPTIONAL MATCH (n)-[r]-()
    RETURN count(r) AS degree
    """, id=node_id)[0]["degree"])

def recent_edges(node_id, limit):
    return run_cypher("""
    MATCH (n:Entity {id:$id})
    MATCH (n)-[r]-(m:Entity)
    RETURN
      startNode(r).id AS source_id,
      startNode(r).name AS source_name,
      startNode(r).entity_type AS source_type,
      type(r) AS relation,
      endNode(r).id AS target_id,
      endNode(r).name AS target_name,
      endNode(r).entity_type AS target_type,
      r.source_chunk_id AS source_chunk_id,
      r.published_date AS published_date,
      r.evidence AS evidence,
      m.id AS neighbor_id
    ORDER BY coalesce(r.published_date,'') DESC
    LIMIT $limit
    """, id=node_id, limit=int(limit))

def textualize(edges):
    edges = sorted(edges, key=lambda e:e.get("published_date") or "", reverse=True)
    lines, used = [], 0
    for e in edges:
        line = (
            f"{e['source_name']} [{e['source_type']}] -{e['relation']}-> "
            f"{e['target_name']} [{e['target_type']}] "
            f"| date={e.get('published_date') or 'unknown'} "
            f"| chunk={e.get('source_chunk_id') or 'unknown'}"
        )
        if e.get("evidence"):
            line += f" | evidence={norm_space(e['evidence'])}"
        if used + len(line) + 1 > MAX_GRAPH_CONTEXT_CHARS:
            break
        lines.append(line)
        used += len(line) + 1
    return "\n".join(lines)

def retrieve_graph_context(query, max_hops=2, edge_limit=50, return_debug=False):
    seeds = match_seeds(query)
    if not seeds:
        out = {"context":"","edges":pd.DataFrame(),
               "diagnostics":{"reason":"NO_SEED","supernode_events":[]}}
        return out if return_debug else ""

    frontier = deque((x["id"],0) for x in seeds)
    expanded, seen_edges, collected = set(), set(), []
    supernode_events = []

    while frontier and len(collected) < GLOBAL_EDGE_CAP:
        node_id, hop = frontier.popleft()
        if node_id in expanded or hop >= max_hops:
            continue
        expanded.add(node_id)

        degree = node_degree(node_id)
        limit = int(edge_limit)
        if degree > SUPER_NODE_DEGREE:
            limit = min(limit, SUPER_NODE_EDGE_CAP)
            supernode_events.append({"node_id":node_id,"degree":degree,"limit":limit})

        for e in recent_edges(node_id, limit):
            key = (e["source_id"],e["relation"],e["target_id"],e["source_chunk_id"])
            if key in seen_edges:
                continue
            seen_edges.add(key)
            collected.append(e)
            if len(collected) >= GLOBAL_EDGE_CAP:
                break

            nb = e.get("neighbor_id")
            if nb and nb not in expanded and hop + 1 < max_hops:
                frontier.append((nb, hop+1))

    out = {
        "context": textualize(collected),
        "edges": pd.DataFrame(collected),
        "diagnostics": {
            "matched_seeds": seeds,
            "expanded_nodes": len(expanded),
            "collected_edges": len(collected),
            "supernode_events": supernode_events,
        }
    }
    return out if return_debug else out["context"]

In [ ]:
#@title 3.4 — Flat answer vs Hybrid GraphRAG answer
ANSWER_SYSTEM = """
Answer only from supplied context.
Be concise but complete. Do not invent facts.
Cite provenance inline as [chunk_id=...] whenever possible.
If evidence is insufficient or conflicting, say so.
""".strip()

def generate_answer(question, context):
    prompt = f"QUESTION:\n{question}\n\nCONTEXT:\n{context}\n\nANSWER:"
    t0 = time.perf_counter()
    text, usage = groq_chat(
        [{"role":"system","content":ANSWER_SYSTEM},
         {"role":"user","content":prompt}],
        model=GROQ_MODEL
    )
    return {
        "answer": text.strip(),
        "latency_s": time.perf_counter()-t0,
        "total_tokens": usage.get("total_tokens"),
    }

def answer_flat_rag(question):
    context, retrieved = retrieve_flat_context(question, k=6)
    out = generate_answer(question, context)
    out.update({"context":context,"retrieved":retrieved})
    return out

def answer_graph_rag(question):
    g = retrieve_graph_context(question, max_hops=2, edge_limit=50, return_debug=True)
    vctx, vdocs = retrieve_flat_context(question, k=4)
    context = f"=== GRAPH ===\n{g['context']}\n\n=== VECTOR ===\n{vctx}"
    out = generate_answer(question, context)
    out.update({"context":context,"graph_debug":g,"vector_docs":vdocs})
    return out

In [21]:
#@title 3.4 — Flat answer vs Hybrid GraphRAG answer
ANSWER_SYSTEM = """
Answer only from supplied context.
Be concise but complete. Do not invent facts.
Cite provenance inline as [chunk_id=...] whenever possible.
If evidence is insufficient or conflicting, say so.
""".strip()

def generate_answer(question, context):
    prompt = f"QUESTION:\n{question}\n\nCONTEXT:\n{context}\n\nANSWER:"
    t0 = time.perf_counter()
    text, usage = openai_chat(
        [{"role":"system","content":ANSWER_SYSTEM},
         {"role":"user","content":prompt}],
        model=OPENAI_MODEL
    )
    return {
        "answer": text.strip(),
        "latency_s": time.perf_counter()-t0,
        "total_tokens": usage.get("total_tokens"),
    }

def answer_flat_rag(question):
    context, retrieved = retrieve_flat_context(question, k=6)
    out = generate_answer(question, context)
    out.update({"context":context,"retrieved":retrieved})
    return out

def answer_graph_rag(question):
    g = retrieve_graph_context(question, max_hops=2, edge_limit=50, return_debug=True)
    vctx, vdocs = retrieve_flat_context(question, k=4)
    context = f"=== GRAPH ===\n{g['context']}\n\n=== VECTOR ===\n{vctx}"
    out = generate_answer(question, context)
    out.update({"context":context,"graph_debug":g,"vector_docs":vdocs})
    return out

# PHẦN 4 — GOLDEN DATASET & LLM-AS-A-JUDGE (75–105')

## Golden schema
`id`, `group`, `question`, `reference_answer`, optional `reference_evidence`.

Notebook có 5 câu starter. Các câu phụ thuộc data dump phải điền gold answer thật trước final evaluation.

In [22]:
#@title 4.1 — 5 câu Golden starter
# GOLDEN_PATH da dinh nghia o cell 1.2 = REPO/data/golden_dataset.csv

starter_golden = pd.DataFrame([
    {
        "id":"G01","group":"factoid",
        "question":"Who was the CEO of Hugging Face in 2023?",
        "reference_answer":"Clément Delangue",
        "reference_evidence":"Validate against instructor dump."
    },
    {
        "id":"G02","group":"multi-hop",
        "question":"Which startups were founded by former Microsoft employees and later received investment from Google?",
        "reference_answer":"",
        "reference_evidence":"TO_BE_FILLED_FROM_DATASET"
    },
    {
        "id":"G03","group":"cross-doc",
        "question":"Compare the direction of AI-related investments by Meta and Apple during 2023 using evidence from multiple articles.",
        "reference_answer":"",
        "reference_evidence":"TO_BE_FILLED_FROM_DATASET"
    },
    {
        "id":"G04","group":"multi-hop",
        "question":"Find a company invested in by a major technology company that also developed a named AI technology; identify both relations and dates.",
        "reference_answer":"",
        "reference_evidence":"TO_BE_FILLED_FROM_DATASET"
    },
    {
        "id":"G05","group":"cross-doc",
        "question":"Identify one technology connected to the same company in at least two news chunks and summarize how the relationship changed over time.",
        "reference_answer":"",
        "reference_evidence":"TO_BE_FILLED_FROM_DATASET"
    },
])

golden_df = pd.read_csv(GOLDEN_PATH) if Path(GOLDEN_PATH).exists() else starter_golden.copy()
display(golden_df)

def validate_golden(df, require_answers=True):
    required = {"id","group","question","reference_answer"}
    if not required.issubset(df.columns):
        raise ValueError(f"Missing columns: {required-set(df.columns)}")
    if require_answers and df.reference_answer.fillna("").str.strip().eq("").any():
        display(df[df.reference_answer.fillna("").str.strip().eq("")][["id","question"]])
        raise ValueError("Điền reference_answer trước final evaluation.")
    print("✅ Golden Dataset valid.")

,id,group,question,reference_answer,reference_evidence
0,G5000-26,multi-hop,"What external technology provider is named inside Amazon's July AI-service expansion, and what other new AI capabili...",Amazon's AI-service story names access to technology from Cohere. It also mentions a program for building more conve...,row 2532 (2023-07-26 20:19:00): Exclusive: Amazon has drawn thousands to try its AI service competing with Microsoft...
1,G5000-27,cross-doc,How should the graph reconcile the statement that AMD powers multiple cloud services with the later Reuters report a...,The June 1 investment article broadly says AMD powers multiple cloud services through its chips. The June 14 Reuters...,row 3357 (2023-06-01 13:16:00): 3 Best Cloud Stocks to Buy in June | row 2905 (2023-06-14 08:47:00): Exclusive: Amaz...
2,G5000-28,multi-hop,"Which model providers are connected to Google Cloud Next '23 in the selected data, and which models are associated w...",Meta is connected via Llama 2 and Code Llama; the Technology Innovation Institute is connected via Falcon LLM; Anthr...,row 3395 (2023-08-29 18:07:00): Google Cloud Kicks Off Next '23 with a New Way to Cloud
3,G5000-29,cross-doc,How did participation in White House AI commitments broaden from July to September 2023 according to the selected re...,"The July report names seven companies including Google, Meta, and OpenAI as making voluntary AI commitments. The Sep...",row 3380 (2023-07-21 13:01:00): The White House and big tech companies release commitments on managing AI | row 3330...
4,G5000-30,multi-hop,"Meta appears in two different AI contexts in the selected data. What are they, and what distinct relation should the...","At Google Cloud Next, Meta is the provider/source of Llama 2 and Code Llama models made available on Google Cloud. S...",row 3395 (2023-08-29 18:07:00): Google Cloud Kicks Off Next '23 with a New Way to Cloud | row 3380 (2023-07-21 13:01...
5,G5000-31,multi-hop,"Order OpenAI's ecosystem moves from March through July 2023 using the selected sources: plug-ins, open-source model ...",March: ChatGPT gained support for about a dozen application plug-ins. May: OpenAI was reported to be preparing a new...,row 3938 (2023-03-24 15:58:00): OpenAI's ChatGPT gets support for a dozen application plug-ins | row 946 (2023-05-15...
6,G5000-32,cross-doc,What is the difference between OpenAI's March plug-in development and its June reported app-store plan?,The March story describes ChatGPT gaining support for application plug-ins so companies can expose product functiona...,row 3938 (2023-03-24 15:58:00): OpenAI's ChatGPT gets support for a dozen application plug-ins | row 2449 (2023-06-2...
7,G5000-33,cross-doc,"Which July OpenAI-related event is a content/technology collaboration, and which July event is a voluntary governanc...",The AP–OpenAI agreement is a collaboration to share access to select news content and technology for generative-AI u...,row 366 (2023-07-13 00:00:00): AP Open AI agree to share select news content and technology in new collaboration | r...
8,G5000-34,multi-hop,Compare how Google Cloud and Amazon expanded their AI ecosystems in the selected data. Which third-party model/techn...,"Google Cloud announced models from Meta (Llama 2 and Code Llama), the Technology Innovation Institute (Falcon LLM), ...",row 3395 (2023-08-29 18:07:00): Google Cloud Kicks Off Next '23 with a New Way to Cloud | row 2532 (2023-07-26 20:19...
9,G5000-35,cross-doc,Contrast AWS's AMD-chip posture with HPE's AI-cloud posture. Which is a tentative hardware sourcing decision and whi...,"AWS was only considering AMD's new AI chips, with no final decision. HPE said it would offer a cloud computing servi...",row 2905 (2023-06-14 08:47:00): Exclusive: Amazon's cloud unit is considering AMD's new AI chips | row 3289 (2023-06...
10,G5000-36,cross-doc,"Rows 2532 and 2537 have near-identical Amazon AI headlines. What single event should be stored, and what details can...",They should be stored as one Amazon AI-service expansion story competing with Microsoft and Google. Safe unioned det...,row 2532 (2023-07-26 20:19:00): Exclusive: Amazon has drawn thousands to try its AI service competing with Microsoft...
11,G5000-37,cross-doc,What evidence shows Dell NativeEdge moving from a May product announcement to a July use-case description?,The May Dell Technologies World report says Dell released NativeEdge. A July networking article describes NativeEdge...,row 4407 (2023-05-24 02:49:00): Projects become products: Dell unveils its long-term game plan for the edge | row 49...
12,G5000-38,multi-hop,How do Dell's APEX Cloud Platforms and NativeEdge represent two different infrastructure layers in its portfolio?,APEX Cloud Platforms are presented as part of Dell's cloud-smart/multicloud strategy and integrate services from Mic...,row 1808 (2023-05-26 14:56:00): From multicloud challenges to ‘cloud-smart’ solutions: How Dell is simplifying multi...
13,G5000-39,multi-hop,What two strategic capability areas did HPE expand in 2023 through the Axis Security deal and its later AI cloud ann...,"HPE moved to expand edge-to-cloud security by agreeing to acquire Axis Security, enabling a unified SASE offering. L...",row 4762 (2023-03-02 22:32:00): Hewlett Packard Enterprise Fortifies Network Security With Acquisition of Security S...
14,G5000-40,cross-doc,Compare Dell and HPE's cloud strategies in the selected scope: which one explicitly integrates Microsoft Azure servi...,Dell's APEX Cloud Platforms story explicitly says the platform integrates services from Microsoft Azure. HPE's story...,row 1808 (2023-05-26 14:56:00): From multicloud challenges to ‘cloud-smart’ solutions: How Dell is simplifying multi...
15,G5000-41,factoid,"Which company did HPE agree to acquire to expand edge-to-cloud security, and what unified security architecture did ...",Axis Security; a unified Secure Access Service Edge (SASE) solution.,row 4762 (2023-03-02 22:32:00): Hewlett Packard Enterprise Fortifies Network Security With Acquisition of Security S...
16,G5000-42,multi-hop,"Starting from the edge-computing concept, connect one Dell product and one HPE transaction to two different edge-rel...",Dell NativeEdge is described as helping deploy and manage edge computing applications and infrastructure. HPE's plan...,row 4997 (2023-07-17 00:00:00): Networking and communication | row 4762 (2023-03-02 22:32:00): Hewlett Packard Enter...
17,G5000-43,cross-doc,Which came first in the selected HPE timeline: the Axis Security acquisition agreement or the LLM-focused cloud serv...,"The Axis Security acquisition agreement came first on March 2, 2023; the HPE LLM-focused cloud service story followe...",row 4762 (2023-03-02 22:32:00): Hewlett Packard Enterprise Fortifies Network Security With Acquisition of Security S...
18,G5000-44,multi-hop,What two distinct partner ecosystems connect L&T Technology Services to advanced infrastructure in 2023: one for urb...,"For urban-rail private 5G, Thales selected L&T Technology Services and Qualcomm. For OT security, L&T Technology Ser...",row 261 (2023-02-23 10:51:00): L&T Technology Services and Qualcomm Selected by Thales for Enabling 5G Private Netwo...
19,G5000-45,cross-doc,Rows 261 and 891 describe L&T Technology Services and Qualcomm being selected by Thales. How should a production gra...,The two reports describe the same Thales selection of L&T Technology Services and Qualcomm for enabling 5G private n...,row 261 (2023-02-23 10:51:00): L&T Technology Services and Qualcomm Selected by Thales for Enabling 5G Private Netwo...
20,G5000-46,cross-doc,Distinguish the cybersecurity relationships in the Keysight–Synopsys article and the LTTS–Palo Alto Networks article...,Keysight and Synopsys are the partners in the IoT-device cybersecurity article. L&T Technology Services and Palo Alt...,row 272 (2023-09-21 16:15:00): Keysight and Synopsys Partner for IoT Device Cybersecurity | row 471 (2023-06-30 08:5...
21,G5000-47,factoid,"In the Keysight–Synopsys IoT cybersecurity record, does the mention of Palo Alto Networks establish Palo Alto as a p...",No. The title identifies Keysight and Synopsys as the partners. Palo Alto Networks appears only as the source of an ...,row 272 (2023-09-21 16:15:00): Keysight and Synopsys Partner for IoT Device Cybersecurity
22,G5000-48,multi-hop,Combine the three Snowflake-related records to summarize Snowflake's role in the 2023 cloud/data ecosystem: what AI ...,H2O.ai launched H2O AI Cloud as a pre-built solution for Snowflake's Manufacturing Data Cloud; Snowflake was listed ...,row 3498 (2023-04-13 16:02:00): H2O.ai Brings H2O AI Cloud to the Snowflake Manufacturing Data Cloud | row 2589 (202...
23,G5000-49,multi-hop,"Across the selected Samsung records, identify three distinct technology domains Samsung is connected to and the spec...",Display/biometric sensing: Samsung unveiled a Sensor OLED Display with an embedded light-sensing organic photodiode ...,row 472 (2023-05-23 22:48:00): Samsung unveils OLED display with embedded heart rate sensor | row 395 (2023-10-05 23...
24,G5000-50,multi-hop,"Compare the chip-related AI positioning of NVIDIA, AMD, and Intel in the selected 5,000-row scope. What distinct sig...",NVIDIA reported that use of its chips for AI services such as chatbots had gone 'through the roof' and its sales out...,row 3432 (2023-02-22 23:36:00): As chatbots boom Nvidia sales outlook beats Wall Street expectations | row 2905 (202...

In [23]:
#@title 4.2 — LLM-as-a-Judge
JUDGE_SYSTEM = """
You are a strict evaluator of RAG answers.
Score 1-5:
- comprehensiveness
- faithfulness to supplied candidate context
- multi_hop_reasoning accuracy
Use the reference answer as correctness anchor.
Return strict JSON only.
""".strip()

def judge_json(system, user):
    if not JUDGE_MODEL:
        raise RuntimeError("Thiếu JUDGE_MODEL.")

    if JUDGE_PROVIDER == "groq":
        return groq_json(system, user, model=JUDGE_MODEL)[0]

    if JUDGE_PROVIDER == "openai":
        if not OPENAI_API_KEY:
            raise RuntimeError("Thiếu OPENAI_API_KEY.")
        from openai import OpenAI
        client = OpenAI(api_key=OPENAI_API_KEY)
        resp = client.chat.completions.create(
            model=JUDGE_MODEL,
            messages=[{"role":"system","content":system},
                      {"role":"user","content":user}],
            temperature=0.0,
            response_format={"type":"json_object"}
        )
        return parse_json_object(resp.choices[0].message.content)

    raise ValueError("JUDGE_PROVIDER must be openai or groq.")

def judge_answer(question, reference, answer, context):
    prompt = f"""
QUESTION:
{question}

REFERENCE:
{reference}

CANDIDATE:
{answer}

CANDIDATE CONTEXT:
{context[:18000]}

Return:
{{
 "comprehensiveness":1,
 "faithfulness":1,
 "multi_hop_reasoning":1,
 "rationale":"2-5 sentences"
}}
"""
    obj = judge_json(JUDGE_SYSTEM, prompt)
    out = {}
    for k in ["comprehensiveness","faithfulness","multi_hop_reasoning"]:
        out[k] = max(1, min(5, int(obj.get(k,1))))
    out["rationale"] = norm_space(obj.get("rationale"))
    return out

In [27]:
#@title 4.3 — Evaluation runner + checkpoint
CHECKPOINT = str(REPO / "data" / "graphrag_eval_checkpoint.csv")  # file tam, da gitignore

def run_evaluation(golden_df):
    rows = []
    for q in tqdm(golden_df.itertuples(index=False), total=len(golden_df), desc="Evaluation"):
        flat = answer_flat_rag(q.question)
        graph = answer_graph_rag(q.question)

        jf = judge_answer(q.question, q.reference_answer, flat["answer"], flat["context"])
        jg = judge_answer(q.question, q.reference_answer, graph["answer"], graph["context"])

        rows.append({
            "id":q.id, "group":q.group, "question":q.question,
            "reference_answer":q.reference_answer,
            "flat_answer":flat["answer"], "graph_answer":graph["answer"],
            "flat_comprehensiveness":jf["comprehensiveness"],
            "graph_comprehensiveness":jg["comprehensiveness"],
            "flat_faithfulness":jf["faithfulness"],
            "graph_faithfulness":jg["faithfulness"],
            "flat_multi_hop_reasoning":jf["multi_hop_reasoning"],
            "graph_multi_hop_reasoning":jg["multi_hop_reasoning"],
            "flat_latency_s":flat["latency_s"],
            "graph_latency_s":graph["latency_s"],
            "flat_total_tokens":flat.get("total_tokens"),
            "graph_total_tokens":graph.get("total_tokens"),
            "flat_judge_rationale":jf["rationale"],
            "graph_judge_rationale":jg["rationale"],
            "graph_supernode_events":len(
                graph["graph_debug"]["diagnostics"].get("supernode_events",[])
            )
        })
        pd.DataFrame(rows).to_csv(CHECKPOINT, index=False)
    return pd.DataFrame(rows)

# CHAY SAU KHI da dien reference_answer that vao data/golden_dataset.csv (plan.md muc 6)
validate_golden(golden_df, require_answers=True)
eval_results_df = run_evaluation(golden_df)
display(eval_results_df)

✅ Golden Dataset valid.

Evaluation:   0%|          | 0/25 [00:00<?, ?it/s]

,id,group,question,reference_answer,flat_answer,graph_answer,flat_comprehensiveness,graph_comprehensiveness,flat_faithfulness,graph_faithfulness,flat_multi_hop_reasoning,graph_multi_hop_reasoning,flat_latency_s,graph_latency_s,flat_total_tokens,graph_total_tokens,flat_judge_rationale,graph_judge_rationale,graph_supernode_events
0,G5000-26,multi-hop,"What external technology provider is named inside Amazon's July AI-service expansion, and what other new AI capabili...",Amazon's AI-service story names access to technology from Cohere. It also mentions a program for building more conve...,The external technology provider named in Amazon's July AI-service expansion is not specified in the provided contex...,"The external technology provider named in Amazon's July AI-service expansion is Synopsys, which is leveraging AI int...",1,1,1,1,1,1,1.741079,1.769859,562,525,The candidate fails to provide any information regarding the external technology provider named in Amazon's July AI-...,The candidate incorrectly identifies Synopsys as the external technology provider named in Amazon's AI-service expan...,0
1,G5000-27,cross-doc,How should the graph reconcile the statement that AMD powers multiple cloud services with the later Reuters report a...,The June 1 investment article broadly says AMD powers multiple cloud services through its chips. The June 14 Reuters...,"The graph should illustrate that while AMD currently powers multiple cloud services, there is ongoing competition an...","The graph should clarify that while AMD currently powers multiple cloud services, the later Reuters report about AWS...",3,3,4,4,3,3,2.482961,2.589777,662,552,The candidate provides a reasonable explanation of the relationship between AMD's current role in powering cloud ser...,The candidate provides a reasonable explanation of the relationship between AMD's current role in cloud services and...,0
2,G5000-28,multi-hop,"Which model providers are connected to Google Cloud Next '23 in the selected data, and which models are associated w...",Meta is connected via Llama 2 and Code Llama; the Technology Innovation Institute is connected via Falcon LLM; Anthr...,The context does not provide specific information about model providers connected to Google Cloud Next '23 or the mo...,The model providers connected to Google Cloud Next '23 in the selected data are:\n\n1. **NVIDIA**\n - Associated M...,1,1,1,1,1,1,0.776675,1.801630,556,1013,The candidate fails to provide any information regarding the model providers connected to Google Cloud Next '23 or t...,The candidate fails to mention the model providers and associated models that are explicitly stated in the reference...,0
3,G5000-29,cross-doc,How did participation in White House AI commitments broaden from July to September 2023 according to the selected re...,"The July report names seven companies including Google, Meta, and OpenAI as making voluntary AI commitments. The Sep...",The provided context does not contain specific information regarding the participation in White House AI commitments...,The provided context does not contain specific information regarding the broadening of participation in White House ...,1,1,1,1,1,1,1.332016,1.480538,529,402,The candidate fails to provide any relevant information regarding the participation in White House AI commitments fr...,The candidate fails to provide any information regarding the broadening of participation in White House AI commitmen...,0
4,G5000-30,multi-hop,"Meta appears in two different AI contexts in the selected data. What are they, and what distinct relation should the...","At Google Cloud Next, Meta is the provider/source of Llama 2 and Code Llama models made available on Google Cloud. S...","Meta appears in two different AI contexts in the selected data:\n\n1. **AI as a General Topic**: In this context, Me...","Meta appears in two different AI contexts:\n\n1. **AI in Chip Design and EDA**: In this context, Meta (as Synopsys) ...",1,1,1,1,1,1,3.911080,2.585738,788,647,The candidate fails to accurately identify the two distinct contexts of Meta as described in the reference answer. I...,"The candidate fails to address the two distinct contexts of Meta as outlined in the reference answer. Instead, it in...",0
5,G5000-31,multi-hop,"Order OpenAI's ecosystem moves from March through July 2023 using the selected sources: plug-ins, open-source model ...",March: ChatGPT gained support for about a dozen application plug-ins. May: OpenAI was reported to be preparing a new...,"From March through July 2023, OpenAI's ecosystem moves can be ordered as follows:\n\n1. **March 2023**: OpenAI annou...",The order of OpenAI's ecosystem moves from March through July 2023 is as follows:\n\n1. **March 2023**: OpenAI annou...,1,1,1,1,1,1,2.062685,3.072850,722,593,The candidate's ordering of OpenAI's ecosystem moves is incorrect and does not align with the reference answer. It m...,The candidate fails to accurately represent the timeline of OpenAI's ecosystem moves as specified in the reference. ...,0
6,G5000-32,cross-doc,What is the difference between OpenAI's March plug-in development and its June reported app-store plan?,The March story describes ChatGPT gaining support for application plug-ins so companies can expose product functiona...,The provided context does not contain specific information regarding OpenAI's March plug-in development or its June ...,The context provided does not contain specific information about OpenAI's March plug-in development or its June repo...,1,1,1,1,1,1,0.846830,0.934825,561,430,The candidate fails to provide any information regarding the differences between OpenAI's March plug-in development ...,The candidate fails to provide any information regarding the differences between OpenAI's March plug-in development ...,0
7,G5000-33,cross-doc,"Which July OpenAI-related event is a content/technology collaboration, and which July event is a voluntary governanc...",The AP–OpenAI agreement is a collaboration to share access to select news content and technology for generative-AI u...,"The July OpenAI-related event that is a content/technology collaboration is the ""BUSINESS GOVirtual Expo and Confere...",The July OpenAI-related event that is a content/technology collaboration is not specified in the provided context. T...,1,1,1,1,1,1,1.560859,1.003914,685,459,The candidate incorrectly identifies the 'BUSINESS GOVirtual Expo and Conference 2023' as the content/technology col...,"The candidate fails to identify any specific events related to OpenAI in July, which are crucial to answering the qu...",0
8,G5000-34,multi-hop,Compare how Google Cloud and Amazon expanded their AI ecosystems in the selected data. Which third-party model/techn...,"Google Cloud announced models from Meta (Llama 2 and Code Llama), the Technology Innovation Institute (Falcon LLM), ...","Google Cloud and Amazon have both expanded their AI ecosystems through strategic partnerships and offerings, but spe...","Google Cloud expanded its AI ecosystem by partnering with UJET, a strategic technology partner that supports the ext...",2,1,3,1,2,1,2.757407,1.172174,671,618,The candidate provides some information about Google Cloud's partnership with UJET but fails to mention the specific...,The candidate only discusses Google Cloud's partnership with UJET and fails to provide any information about Amazon'...,0
9,G5000-35,cross-doc,Contrast AWS's AMD-chip posture with HPE's AI-cloud posture. Which is a tentative hardware sourcing decision and whi...,"AWS was only considering AMD's new AI chips, with no final decision. HPE said it would offer a cloud computing servi...",The context provided does not contain specific information about AWS's AMD-chip posture or HPE's AI-cloud posture. T...,The context provided does not contain specific information about AWS's AMD-chip posture or HPE's AI-cloud posture. T...,1,1,1,1,1,1,1.645324,0.897984,564,483,"The candidate fails to provide any relevant information regarding AWS's AMD-chip posture or HPE's AI-cloud posture, ...","The candidate fails to address the specific question regarding AWS's AMD-chip posture and HPE's AI-cloud posture, le...",0
10,G5000-36,cross-doc,"Rows 2532 and 2537 have near-identical Amazon AI headlines. What single event should be stored, and what details can...",They should be stored as one Amazon AI-service expansion story competing with Microsoft and Google. Safe unioned det...,The single event that should be stored is the European Union's investigation into Amazon's $1.7 billion purchase of ...,The single event that should be stored is the European Union's investigation into Amazon.com Inc.'s $1.7 billion pur...,1,1,1,1,1,1,2.902421,2.528292,663,518,"The candidate answer is completely off-topic, discussing an EU investigation into Amazon's acquisition of iRobot ins...",The candidate answer does not address the question regarding Amazon AI headlines and instead focuses on a separate e...,0
11,G5000-37,cross-doc,What evidence shows Dell NativeEdge moving from a May product announcement to a July use-case description?,The May Dell Technologies World report says Dell released NativeEdge. A July networking article describes NativeEdge...,The provided context does not contain any evidence regarding Dell NativeEdge moving from a May product announcement ...,The provided context does not contain any evidence regarding Dell NativeEdge moving from a May product announcement ...,1,1,1,1,1,1,0.823019,1.131305,558,426,The candidate fails to provide any evidence or context regarding the transition of Dell NativeEdge from a May produc...,The candidate fails to provide any evidence or details regarding the transition of Dell NativeEdge from a May announ...,0
12,G5000-38,multi-hop,How do Dell's APEX Cloud Platforms and NativeEdge represent two different infrastructure layers in its portfolio?,APEX Cloud Platforms are presented as part of Dell's cloud-smart/multicloud strategy and integrate services from Mic...,Dell's APEX Cloud Platforms and NativeEdge represent two distinct infrastructure layers in its portfolio. APEX Cloud...,Dell's APEX Cloud Platforms and NativeEdge represent two distinct infrastructure layers in its portfolio. APEX Cloud...,4,4,5,4,4,4,1.793080,2.258127,685,553,"The candidate provides a clear distinction between APEX Cloud Platforms and NativeEdge, accurately reflecting their ...","The candidate provides a clear distinction between APEX Cloud Platforms and NativeEdge, addressing their respective ...",0
13,G5000-39,multi-hop,What two strategic capability areas did HPE expand in 2023 through the Axis Security deal and its later AI cloud ann...,"HPE moved to expand edge-to-cloud security by agreeing to acquire Axis Security, enabling a unified SASE offering. L...",HPE expanded its strategic capability areas in 2023 through the Axis Security deal and its later AI cloud announceme...,The two strategic capability areas that HPE expanded in 2023 through the Axis Security deal and its later AI cloud a...,2,2,2,2,2,2,0.894008,0.881579,539,492,"The candidate answer identifies the strategic areas as cybersecurity and AI capabilities, which is partially correct...","The candidate identifies the two strategic capability areas as cybersecurity and AI cloud services, which partially ...",0
14,G5000-40,cross-doc,Compare Dell and HPE's cloud strategies in the selected scope: which one explicitly integrates Microsoft Azure servi...,Dell's APEX Cloud Platforms story explicitly says the platform integrates services from Microsoft Azure. HPE's story...,"The provided context does not explicitly mention Dell or HPE's cloud strategies, including their integration with Mi...","The provided context does not contain specific information regarding Dell and HPE's cloud strategies, particularly i...",1,1,1,1,1,1,0.836966,1.657124,549,440,"The candidate fails to address the question regarding the cloud strategies of Dell and HPE, as it does not reference...","The candidate fails to provide any relevant information regarding Dell and HPE's cloud strategies, which is essentia...",0
15,G5000-41,factoid,"Which company did HPE agree to acquire to expand edge-to-cloud security, and what unified security architecture did ...",Axis Security; a unified Secure Access Service Edge (SASE) solution.,"The context does not provide information about which company HPE agreed to acquire to expand edge-to-cloud security,...","HPE agreed to acquire a company to expand edge-to-cloud security, but the specific company is not mentioned in the p...",1,1,1,1,1,1,1.020788,0.822420,570,428,The candidate answer correctly identifies that the context does not provide the necessary information to answer the ...,"The candidate fails to provide the specific company HPE agreed to acquire, which is crucial for comprehensiveness. I...",0
16,G5000-42,multi-hop,"Starting from the edge-computing concept, connect one Dell product and one HPE transaction to two different edge-rel...",Dell NativeEdge is described as helping deploy and manage edge computing applications and infrastructure. HPE's plan...,"One Dell product related to edge computing is the Dell Edge Gateway, which enables data processing at the edge of ne...","From the edge-computing concept, one Dell product that can be connected to an edge-related outcome is Dell's edge co...",3,2,4,2,3,2,2.999981,3.648206,708,502,"The candidate provides relevant Dell and HPE products related to edge computing, but it does not accurately reflect ...",The candidate provides some relevant information about Dell's edge computing solutions and HPE's collaboration for e...,0
17,G5000-43,cross-doc,Which came first in the selected HPE timeline: the Axis Security acquisition agreement or the LLM-focused cloud serv...,"The Axis Security acquisition agreement came first on March 2, 2023; the HPE LLM-focused cloud service story followe...",The context provided does not include specific information about the Axis Security acquisition agreement or the LLM-...,The context provided does not include specific dates or details regarding the Axis Security acquisition agreement or...,1,1,1,1,1,1,0.979775,1.591576,623,435,The candidate fails to provide any information regarding the Axis Security acquisition agreement or the LLM-focused ...,"The candidate fails to provide any information regarding the specific events in question, namely the Axis Security a...",0
18,G5000-44,multi-hop,What two distinct partner ecosystems connect L&T Technology Services to advanced infrastructure in 2023: one for urb...,"For urban-rail private 5G, Thales selected L&T Technology Services and Qualcomm. For OT security, L&T Technology Ser...",L&T Technology Services connects to advanced infrastructure in 2023 through two distinct partner ecosystems: one for...,L&T Technology Services is connected to advanced infrastructure in 2023 through two distinct partner ecosystems: one...,2,4,2,5,2,4,1.088874,1.029778,607,433,The candidate provides partial information about the partner ecosystems but fails to mention the specific partner fo...,The candidate accurately identifies the two partner ecosystems: Thales for urban-rail 5G and Palo Alto Networks for ...,0
19,G5000-45,cross-doc,Rows 261 and 891 describe L&T Technology Services and Qualcomm being selected by Thales. How should a production gra...,The two reports describe the same Thales selection of L&T Technology Services and Qualcomm for enabling 5G private n...,"To avoid double-counting L&T Technology Services and Qualcomm being selected by Thales in a production graph, the gr...",To avoid double-counting in a production graph regarding L&T Technology Services and Qualcomm being selected by Thal...,3,4,4,5,3,4,2.107909,1.974285,641,490,The candidate provides a reasonable approach to avoid double-counting by suggesting a single edge connecting Thales ...,The candidate provides a clear explanation of how to avoid double-counting by representing the selection as a single...,0
20,G5000-46,cross-doc,Distinguish the cybersecurity relationships in the Keysight–Synopsys article and the LTTS–Palo Alto Networks article...,Keysight and Synopsys are the partners in the IoT-device cybersecurity article. L&T Technology Services and Palo Alt...,"The Keysight–Synopsys article focuses on IoT-device cybersecurity, as it pertains to securing connected devices and ...","The Keysight–Synopsys article focuses on IoT-device cybersecurity, as it discusses the integration of AI into chip d...",5,5,5,5,5,5,2.309227,2.192796,570,565,"The candidate accurately distinguishes between the two articles, correctly identifying the Keysight–Synopsys article...","The candidate accurately distinguishes between the two articles, correctly identifying the Keysight–Synopsys article...",0
21,G5000-47,factoid,"In the Keysight–Synopsys IoT cybersecurity record, does the mention of Palo Alto Networks establish Palo Alto as a p...",No. The title identifies Keysight and Synopsys as the partners. Palo Alto Networks appears only as the source of an ...,The provided context does not mention Palo Alto Networks in relation to the Keysight–Synopsys IoT cybersecurity reco...,The provided context does not mention Palo Alto Networks in relation to the Keysight–Synopsys IoT cybersecurity reco...,3,2,3,2,3,2,1.469251,0.922582,575,477,The candidate correctly states that the context does not establish Palo Alto Networks as a partner in the Keysight–S...,The candidate answer correctly states that there is no mention of Palo Alto Networks as a partner in the Keysight–Sy...,0
22,G5000-48,multi-hop,Combine the three Snowflake-related records to summarize Snowflake's role in the 2023 cloud/data ecosystem: what AI ...,H2O.ai launched H2O AI Cloud as a pre-built solution for Snowflake's Manufacturing Data Cloud; Snowflake was listed ...,"In 2023, Snowflake plays a significant role in the cloud/data ecosystem through its integration with artificial inte...","In 2023, Snowflake plays a significant role in the cloud/data ecosystem through its integration with AI, market reco...",3,2,4,2,3,2,3.110316,4.102969,841,693,"The candidate provides a summary of Snowflake's role in the cloud/data ecosystem, touching on AI integration, market...",The candidate provides a summary of Snowflake's role in the 2023 cloud/data ecosystem but lacks specific details fro...,0
23,G5000-49,multi-hop,"Across the selected Samsung records, identify three distinct technology domains Samsung is connected to and the spec...",Display/biometric sensing: Samsung unveiled a Sensor OLED Display with an embedded light-sensing organic photodiode ...,"Based on the provided context, three distinct technology domains that Samsung is connected to are:\n\n1. **Data Tech...",Samsung is connected to the following three distinct technology domains:\n\n1. **Artificial Intelligence (AI)**: Evi...,1,1,1,1,1,1,3.274740,3.671315,689,599,"The candidate fails to identify the technology domains mentioned in the reference answer, which are display/biometri...","The candidate fails to identify the specific technology domains mentioned in the reference answer, such as Display/b...",0
24,G5000-50,multi-hop,"Compare the chip-related AI positioning of NVIDIA, AMD, and Intel in the selected 5,000-row scope. What distinct sig...",NVIDIA reported that use of its chips for AI services such as chatbots had gone 'through the roof' and its sales out...,"NVIDIA, AMD, and Intel each have distinct positions in the AI chip market:\n\n1. **NVIDIA**: The company is actively...","NVIDIA, AMD, and Intel each have distinct positions in the AI chip landscape:\n\n1. **NVIDIA**: The company is activ...",2,2,2,2,2,2,4.281598,3.915894,822,1316,"The candidate provides some relevant information about NVIDIA, AMD, and Intel, but it diverges from the reference by...","The candidate provides some relevant information about NVIDIA's partnership and Intel's chip development, but it lac...",0

In [26]:
#@title 4.2 — LLM-as-a-Judge
JUDGE_SYSTEM = """
You are a strict evaluator of RAG answers.
Score 1-5:
- comprehensiveness
- faithfulness to supplied candidate context
- multi_hop_reasoning accuracy
Use the reference answer as correctness anchor.
Return strict JSON only.
""".strip()

def judge_json(system, user):
    return openai_json(system, user, model=OPENAI_MODEL)[0]

def judge_answer(question, reference, answer, context):
    prompt = f"""
QUESTION:
{question}

REFERENCE:
{reference}

CANDIDATE:
{answer}

CANDIDATE CONTEXT:
{context[:18000]}

Return:
{{
 "comprehensiveness":1,
 "faithfulness":1,
 "multi_hop_reasoning":1,
 "rationale":"2-5 sentences"
}}
"""
    obj = judge_json(JUDGE_SYSTEM, prompt)
    out = {}
    for k in ["comprehensiveness","faithfulness","multi_hop_reasoning"]:
        out[k] = max(1, min(5, int(obj.get(k,1))))
    out["rationale"] = norm_space(obj.get("rationale"))
    return out

In [28]:
#@title 4.4 — Comparison table + export
def comparison_table(eval_df):
    metric_map = {
        "Comprehensiveness":("flat_comprehensiveness","graph_comprehensiveness"),
        "Faithfulness":("flat_faithfulness","graph_faithfulness"),
        "Multi-hop reasoning":("flat_multi_hop_reasoning","graph_multi_hop_reasoning"),
        "Latency (s)":("flat_latency_s","graph_latency_s"),
        "Token usage":("flat_total_tokens","graph_total_tokens"),
    }

    rows = []
    for group, g in eval_df.groupby("group"):
        for metric, (fc,gc) in metric_map.items():
            f = pd.to_numeric(g[fc], errors="coerce").mean()
            gr = pd.to_numeric(g[gc], errors="coerce").mean()

            if metric in {"Latency (s)","Token usage"}:
                comment = "Flat RAG thường rẻ/nhanh hơn." if f < gr else "GraphRAG không đắt hơn trong sample này."
            else:
                delta = gr - f
                if delta >= .75:
                    comment = "GraphRAG cải thiện rõ; kiểm tra rationale và provenance."
                elif delta <= -.5:
                    comment = "Flat RAG tốt hơn; graph extraction/retrieval có thể gây mất thông tin hoặc nhiễu."
                else:
                    comment = "Hai phương pháp gần nhau."

            rows.append({
                "Loại câu hỏi":group, "Metric":metric,
                "Flat RAG":round(f,3) if pd.notna(f) else np.nan,
                "GraphRAG":round(gr,3) if pd.notna(gr) else np.nan,
                "Nhận xét phân tích":comment
            })
    return pd.DataFrame(rows)

comparison_df = comparison_table(eval_results_df)
display(comparison_df)

# README/ASSIGNMENT yeu cau outputs/, RUBRIC 3.3 yeu cau reports/ -> ghi ca hai.
for _d in [OUTPUTS_DIR, REPORTS_DIR]:
    eval_results_df.to_csv(_d / "graphrag_eval_results.csv", index=False)
    comparison_df.to_csv(_d / "graphrag_vs_flatrag_summary.csv", index=False)
    print("exported ->", _d / "graphrag_eval_results.csv")
    print("exported ->", _d / "graphrag_vs_flatrag_summary.csv")

,Loại câu hỏi,Metric,Flat RAG,GraphRAG,Nhận xét phân tích
0,cross-doc,Comprehensiveness,1.727,1.818,Hai phương pháp gần nhau.
1,cross-doc,Faithfulness,1.909,2.000,Hai phương pháp gần nhau.
2,cross-doc,Multi-hop reasoning,1.727,1.818,Hai phương pháp gần nhau.
3,cross-doc,Latency (s),1.621,1.635,Flat RAG thường rẻ/nhanh hơn.
4,cross-doc,Token usage,600.455,472.727,GraphRAG không đắt hơn trong sample này.
5,factoid,Comprehensiveness,2.000,1.500,Flat RAG tốt hơn; graph extraction/retrieval có thể gây mất thông tin hoặc nhiễu.
6,factoid,Faithfulness,2.000,1.500,Flat RAG tốt hơn; graph extraction/retrieval có thể gây mất thông tin hoặc nhiễu.
7,factoid,Multi-hop reasoning,2.000,1.500,Flat RAG tốt hơn; graph extraction/retrieval có thể gây mất thông tin hoặc nhiễu.
8,factoid,Latency (s),1.245,0.873,GraphRAG không đắt hơn trong sample này.
9,factoid,Token usage,572.500,452.500,GraphRAG không đắt hơn trong sample này.
10,multi-hop,Comprehensiveness,1.917,1.833,Hai phương pháp gần nhau.
11,multi-hop,Faithfulness,2.250,1.917,Hai phương pháp gần nhau.
12,multi-hop,Multi-hop reasoning,1.917,1.833,Hai phương pháp gần nhau.
13,multi-hop,Latency (s),2.391,2.493,Flat RAG thường rẻ/nhanh hơn.
14,multi-hop,Token usage,682.500,665.333,GraphRAG không đắt hơn trong sample này.

exported -> /content/lab19/outputs/graphrag_eval_results.csv
exported -> /content/lab19/outputs/graphrag_vs_flatrag_summary.csv
exported -> /content/lab19/reports/graphrag_eval_results.csv
exported -> /content/lab19/reports/graphrag_vs_flatrag_summary.csv

# PHẦN 5 — FAILURE-MODE CHECKS & SUBMISSION (105–120')

Bắt buộc chứng minh:
1. Edge provenance không thiếu.
2. Entity Resolution có audit.
3. Super-node degree > 100 chỉ expand tối đa 50 edge.
4. Có comparison table.

In [29]:
#@title 5.1 — Super-node check + entity audit
def test_supernode_policy():
    rows = run_cypher("""
    MATCH (n:Entity)-[r]-()
    WITH n, count(r) AS degree
    ORDER BY degree DESC LIMIT 1
    RETURN n.id AS id, n.name AS name, degree
    """)
    if not rows:
        print("Graph empty.")
        return

    n = rows[0]
    limit = 50 if n["degree"] > SUPER_NODE_DEGREE else 1000
    edges = recent_edges(n["id"], limit)
    print(n, "fetched=", len(edges))
    if n["degree"] > SUPER_NODE_DEGREE:
        assert len(edges) <= 50
        print("✅ Super-node cap OK.")

def show_resolution_audit(audit_df):
    if audit_df.empty:
        print("No audit rows.")
        return
    display(
        audit_df.sort_values("similarity", ascending=False).head(30)
    )
    print("High-similarity rejected pairs:")
    display(
        audit_df[audit_df.decision=="REJECT_GUARD"]
        .sort_values("similarity", ascending=False)
        .head(20)
    )

test_supernode_policy()
show_resolution_audit(entity_resolution_audit_df)

{'id': 'a1db046fa1cf05904c8cb3a8', 'name': 'Reliance Industries', 'degree': 6} fetched= 6

,type,left,right,similarity,decision
0,Company,Reliance Industries Ltd,Reliance Industries,0.944749,MERGE_VECTOR
1,Company,Activision Blizzard,Activision Blizzard Inc.,0.918492,MERGE_VECTOR
2,Company,Airbnb,Airbnb Inc.,0.874692,MERGE_VECTOR
3,Technology,Chandrayaan-I,Chandrayaan-III,0.858351,MERGE_VECTOR

High-similarity rejected pairs:

Empty DataFrame
Columns: [type, left, right, similarity, decision]
Index: []

## 5.2 — Thuyết minh kỹ thuật: học viên tự điền

1. Coreference sai ở tình huống nào?
2. Entity threshold bao nhiêu, vì sao?
3. Candidate nào similarity cao nhưng không nên merge?
4. Top 3 super-node và degree?
5. Vì sao ưu tiên edge mới nhất có thể đúng/sai?
6. Flat RAG thắng nhóm nào?
7. GraphRAG thắng nhóm nào?
8. Latency/token trade-off?
9. AI Coding Agent đề xuất gì mà bạn **không dùng**, vì sao?
10. Scale 350MB: bottleneck đầu tiên là gì?

# 🎁 BONUS

## A — Low-level / High-level
Tạo local entities và high-level topics/community reports; query router chọn tầng retrieval.

## B — Global Search via Community Reports
Nếu Neo4j instance không có GDS phù hợp, fallback:
1. export edges,
2. NetworkX community detection,
3. `UNWIND` write `community_id`,
4. LLM summarize community,
5. query global trên reports.

## C — Self-Correction Graph Retrieval
- hop 2 → LLM kiểm tra context đủ chưa,
- thiếu → hop 3,
- vẫn thiếu → vector fallback,
- bắt buộc stop condition.

In [30]:
#@title Bonus — NetworkX community fallback
import networkx as nx

def build_communities(limit_edges=20000):
    edge_df = pd.DataFrame(run_cypher("""
    MATCH (a:Entity)-[r]->(b:Entity)
    RETURN a.id AS source, b.id AS target
    LIMIT $limit
    """, limit=int(limit_edges)))

    G = nx.Graph()
    G.add_edges_from(edge_df[["source","target"]].itertuples(index=False, name=None))
    communities = nx.algorithms.community.greedy_modularity_communities(G)

    rows = []
    for cid, members in enumerate(communities):
        rows += [{"id":node_id,"community_id":int(cid)} for node_id in members]

    for b in batches(rows, 1000):
        run_cypher("""
        UNWIND $rows AS row
        MATCH (n:Entity {id:row.id})
        SET n.community_id=row.community_id
        """, rows=b)

    return pd.DataFrame(rows)

# community_df = build_communities()

In [31]:
#@title Bonus — Self-correction scaffold
SUFFICIENCY_SYSTEM = """
Decide whether the supplied retrieval context is sufficient to answer the question faithfully.
Do not answer the question. Return strict JSON only.
""".strip()

def context_sufficient(question, context):
    obj, _ = groq_json(
        SUFFICIENCY_SYSTEM,
        f"""QUESTION: {question}
CONTEXT:
{context[:16000]}
Return {{"sufficient":true,"missing":"..."}}"""
    )
    return bool(obj.get("sufficient")), norm_space(obj.get("missing"))

def self_correcting_context(question):
    g2 = retrieve_graph_context(question, 2, 50, True)
    ok, missing = context_sufficient(question, g2["context"])
    if ok:
        return {"route":"hop2","context":g2["context"],"missing":""}

    g3 = retrieve_graph_context(question, 3, 50, True)
    ok, missing2 = context_sufficient(question, g3["context"])
    if ok:
        return {"route":"hop3","context":g3["context"],"missing":missing}

    flat, _ = retrieve_flat_context(question, k=8)
    return {
        "route":"hop3+vector",
        "context":f"=== GRAPH ===\n{g3['context']}\n\n=== VECTOR ===\n{flat}",
        "missing":missing2
    }

# ✅ RUBRIC

- **30% Chạy được code:** graph nạp thành công, schema đúng, xuất bảng.
- **30% Failure modes:** xử lý ít nhất 2/3 vấn đề Super-node, Entity Resolution, Coreference.
- **20% Evaluation:** chạy hết Golden Dataset, phân tích hợp lý.
- **20% Thuyết minh:** giải thích kiến trúc và cách kiểm soát AI Coding Agent.

## Submission checklist
- [ ] Neo4j connected
- [ ] Dedup/chunking đã chạy
- [ ] Coreference spot-check
- [ ] Entity resolution audit
- [ ] `UNWIND` bulk insert
- [ ] 0 edge thiếu provenance
- [ ] Flat RAG chạy
- [ ] GraphRAG chạy
- [ ] Super-node check
- [ ] Golden Dataset có gold answers thật
- [ ] Evaluation chạy hết
- [ ] Export results + summary CSV
- [ ] Thuyết minh kỹ thuật
- [ ] Bonus (nếu có) có định lượng trước/sau

In [32]:
#@title 5.3 - [COLAB] Commit & push deliverables len GitHub
import subprocess
from pathlib import Path

def _git(*args, redact=None):
    r = subprocess.run(["git", "-C", str(REPO), *args], capture_output=True, text=True)
    out = (r.stdout + r.stderr).strip()
    if redact:
        out = out.replace(redact, "***")
    if out:
        print(out)
    return r.returncode

CANDIDATES = [
    "outputs/graphrag_eval_results.csv",
    "outputs/graphrag_vs_flatrag_summary.csv",
    "outputs/entity_resolution_audit.csv",
    "reports/graphrag_eval_results.csv",
    "reports/graphrag_vs_flatrag_summary.csv",
    "reports/lab_report.md",
    "reports/technical_defense.md",
    "reports/failure_analysis.md",
    "data/golden_dataset.csv",
]
existing = [f for f in CANDIDATES if (REPO / f).exists()]
print("Se commit:", *existing, sep="\n  ")

if not existing:
    print("Chua co file nao de commit.")
else:
    _git("add", "--", *existing)
    _git("status", "--short")
    _git("commit", "-m", "Lab 19: eval results, benchmark summary, entity audit, golden dataset")

    try:
        from google.colab import userdata
        GH_TOKEN = userdata.get("GH_TOKEN")
        push_url = f"https://{GH_USER}:{GH_TOKEN}@github.com/{GH_USER}/{GH_REPO}.git"
        if _git("push", push_url, "HEAD:main", redact=GH_TOKEN) == 0:
            print("\nDa push CSV + report.")
        print("\nCON 1 BUOC NUA: File > Save a copy in GitHub")
        print("  -> repo:", f"{GH_USER}/{GH_REPO}")
        print("  -> path: Day19_GraphRAG_vs_FlatRAG_Production_Lab_Guide.ipynb")
        print("  Buoc nay moi day duoc notebook DA CHAY (kem output) len repo.")
    except Exception as e:
        print("Khong push duoc:", e)

Se commit:
  outputs/graphrag_eval_results.csv
  outputs/graphrag_vs_flatrag_summary.csv
  outputs/entity_resolution_audit.csv
  reports/graphrag_eval_results.csv
  reports/graphrag_vs_flatrag_summary.csv
  reports/lab_report.md
  reports/technical_defense.md
  data/golden_dataset.csv
A  outputs/entity_resolution_audit.csv
A  outputs/graphrag_eval_results.csv
A  outputs/graphrag_vs_flatrag_summary.csv
A  reports/graphrag_eval_results.csv
A  reports/graphrag_vs_flatrag_summary.csv
[main 395b6c4] Lab 19: eval results, benchmark summary, entity audit, golden dataset
 5 files changed, 325 insertions(+)
 create mode 100644 outputs/entity_resolution_audit.csv
 create mode 100644 outputs/graphrag_eval_results.csv
 create mode 100644 outputs/graphrag_vs_flatrag_summary.csv
 create mode 100644 reports/graphrag_eval_results.csv
 create mode 100644 reports/graphrag_vs_flatrag_summary.csv
To https://github.com/ThaiTu2602/K4-Track3-Lab19-GraphRAG_2A202601504.git
   a01d060..395b6c4  HEAD -> main

Da push CSV + report.

CON 1 BUOC NUA: File > Save a copy in GitHub
  -> repo: ThaiTu2602/K4-Track3-Lab19-GraphRAG_2A202601504
  -> path: Day19_GraphRAG_vs_FlatRAG_Production_Lab_Guide.ipynb
  Buoc nay moi day duoc notebook DA CHAY (kem output) len repo.

In [33]:
try:
    print(graph_checks())
except Exception as e:
    print("SKIP graph_checks:", e)

try:
    print(top_degree_df.head(10).to_string())
except Exception as e:
    print("SKIP top_degree_df:", e)

{'nodes': 197, 'edges': 119, 'invalid_provenance_edges': 0}

,id,name,type,degree
0,a1db046fa1cf05904c8cb3a8,Reliance Industries,Company,6
1,7b219357277193c25d37d788,Railergy,Company,5
2,1f2054ff9fad32685f6dda3b,Norwegian University of Life Sciences,Company,4
3,b0f073fc691ac6ea5bfa2c41,Activision Blizzard,Company,4
4,b823fb02e58a12bdc4c38934,NVIDIA,Company,3
5,c2fcf23ba561589b0b1df4ba,US revenues,Technology,3
6,5b619ed690d75481907e2863,Airbnb,Company,3
7,269d5bc0969e0b170f016315,Aaritya Technologies,Company,3
8,8693b055457df450df9cfcdf,Unacademy,Company,3
9,a5ecbacff981ced8953c6ce0,ATOSS Software,Company,2
10,95fdfcdea30320fbcd96b512,A-Mark Precious Metals,Company,2
11,8cc9b1d6d7b00f4190f13dd0,Andreessen Horowitz,Company,2
12,74bd8cb542da5b4c9e6e42ad,Dar Al-Handasah Consultants,Company,2
13,6979b0d4a71ab90434659ac6,Indian Space Research Organisation,Company,2
14,39430d6a0c7aa28d8fe56bf3,Meeno,Company,2

({'nodes': 197, 'edges': 119, 'invalid_provenance_edges': 0},                           id                                   name  \
0   a1db046fa1cf05904c8cb3a8                    Reliance Industries
1   7b219357277193c25d37d788                               Railergy
2   1f2054ff9fad32685f6dda3b  Norwegian University of Life Sciences
3   b0f073fc691ac6ea5bfa2c41                    Activision Blizzard
4   b823fb02e58a12bdc4c38934                                 NVIDIA
5   c2fcf23ba561589b0b1df4ba                            US revenues
6   5b619ed690d75481907e2863                                 Airbnb
7   269d5bc0969e0b170f016315                   Aaritya Technologies
8   8693b055457df450df9cfcdf                              Unacademy
9   a5ecbacff981ced8953c6ce0                         ATOSS Software
10  95fdfcdea30320fbcd96b512                 A-Mark Precious Metals
11  8cc9b1d6d7b00f4190f13dd0                    Andreessen Horowitz
12  74bd8cb542da5b4c9e6e42ad            Dar Al-Handasah Consultants
13  6979b0d4a71ab90434659ac6     Indian Space Research Organisation
14  39430d6a0c7aa28d8fe56bf3                                  Meeno

          type  degree
0      Company       6
1      Company       5
2      Company       4
3      Company       4
4      Company       3
5   Technology       3
6      Company       3
7      Company       3
8      Company       3
9      Company       2
10     Company       2
11     Company       2
12     Company       2
13     Company       2
14     Company       2  )
                         id                                   name        type  degree
0  a1db046fa1cf05904c8cb3a8                    Reliance Industries     Company       6
1  7b219357277193c25d37d788                               Railergy     Company       5
2  1f2054ff9fad32685f6dda3b  Norwegian University of Life Sciences     Company       4
3  b0f073fc691ac6ea5bfa2c41                    Activision Blizzard     Company       4
4  b823fb02e58a12bdc4c38934                                 NVIDIA     Company       3
5  c2fcf23ba561589b0b1df4ba                            US revenues  Technology       3
6  5b619ed690d75481907e2863                                 Airbnb     Company       3
7  269d5bc0969e0b170f016315                   Aaritya Technologies     Company       3
8  8693b055457df450df9cfcdf                              Unacademy     Company       3
9  a5ecbacff981ced8953c6ce0                         ATOSS Software     Company       2